# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mmu', [dirname(__file__)])
        except ImportError:
            import _mmu
            return _mmu
        if fp is not None:
            try:
                _mod = imp.load_module('_mmu', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mmu = swig_import_helper()
    del swig_import_helper
else:
    import _mmu
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class trace(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, trace, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, trace, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mmu.new_trace()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["isActive"] = _mmu.trace_isActive_set
    __swig_getmethods__["isActive"] = _mmu.trace_isActive_get
    if _newclass:
        isActive = _swig_property(_mmu.trace_isActive_get, _mmu.trace_isActive_set)
    __swig_setmethods__["path"] = _mmu.trace_path_set
    __swig_getmethods__["path"] = _mmu.trace_path_get
    if _newclass:
        path = _swig_property(_mmu.trace_path_get, _mmu.trace_path_set)

    def dumpMsg(self, fmt: 'char const *') -> "void":
        return _mmu.trace_dumpMsg(self, fmt)

    def dumpUserMsg(self, fmt: 'char const *') -> "void":
        return _mmu.trace_dumpUserMsg(self, fmt)

    def dumpWarning(self, fmt: 'char const *') -> "void":
        return _mmu.trace_dumpWarning(self, fmt)

    def setComponent(self, comp: 'component') -> "void":
        return _mmu.trace_setComponent(self, comp)
    __swig_destroy__ = _mmu.delete_trace
    __del__ = lambda self: None
trace_swigregister = _mmu.trace_swigregister
trace_swigregister(trace)

class slavePort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, slavePort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, slavePort, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mmu.new_slavePort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_slavePort
    __del__ = lambda self: None

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.slavePort_getSlavePortResync(self, initiatorEngine, targetEngine)

    def setName(self, name: 'string') -> "void":
        return _mmu.slavePort_setName(self, name)

    def setComp(self, comp: 'component') -> "void":
        return _mmu.slavePort_setComp(self, comp)

    def getPortClass(self) -> "unsigned long long":
        return _mmu.slavePort_getPortClass(self)
    __swig_setmethods__["comp"] = _mmu.slavePort_comp_set
    __swig_getmethods__["comp"] = _mmu.slavePort_comp_get
    if _newclass:
        comp = _swig_property(_mmu.slavePort_comp_get, _mmu.slavePort_comp_set)
    __swig_setmethods__["name"] = _mmu.slavePort_name_set
    __swig_getmethods__["name"] = _mmu.slavePort_name_get
    if _newclass:
        name = _swig_property(_mmu.slavePort_name_get, _mmu.slavePort_name_set)

    def getName(self) -> "char *":
        return _mmu.slavePort_getName(self)
    __swig_setmethods__["next"] = _mmu.slavePort_next_set
    __swig_getmethods__["next"] = _mmu.slavePort_next_get
    if _newclass:
        next = _swig_property(_mmu.slavePort_next_get, _mmu.slavePort_next_set)
    __swig_setmethods__["slaveId"] = _mmu.slavePort_slaveId_set
    __swig_getmethods__["slaveId"] = _mmu.slavePort_slaveId_get
    if _newclass:
        slaveId = _swig_property(_mmu.slavePort_slaveId_get, _mmu.slavePort_slaveId_set)
slavePort_swigregister = _mmu.slavePort_swigregister
slavePort_swigregister(slavePort)

class inPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, inPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, inPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _mmu.inPort_data_set
    __swig_getmethods__["data"] = _mmu.inPort_data_get
    if _newclass:
        data = _swig_property(_mmu.inPort_data_get, _mmu.inPort_data_set)
    __swig_setmethods__["comp"] = _mmu.inPort_comp_set
    __swig_getmethods__["comp"] = _mmu.inPort_comp_get
    if _newclass:
        comp = _swig_property(_mmu.inPort_comp_get, _mmu.inPort_comp_set)
    __swig_setmethods__["targetComp"] = _mmu.inPort_targetComp_set
    __swig_getmethods__["targetComp"] = _mmu.inPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_mmu.inPort_targetComp_get, _mmu.inPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _mmu.inPort_targetEval_set
    __swig_getmethods__["targetEval"] = _mmu.inPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_mmu.inPort_targetEval_get, _mmu.inPort_targetEval_set)
    __swig_setmethods__["widthWords"] = _mmu.inPort_widthWords_set
    __swig_getmethods__["widthWords"] = _mmu.inPort_widthWords_get
    if _newclass:
        widthWords = _swig_property(_mmu.inPort_widthWords_get, _mmu.inPort_widthWords_set)

    def checkTarget(self) -> "void":
        return _mmu.inPort_checkTarget(self)

    def read32(self) -> "uint32_t":
        return _mmu.inPort_read32(self)

    def readAt(self, wordIndex: 'int') -> "uint32_t":
        return _mmu.inPort_readAt(self, wordIndex)

    def copy(self, data: 'uint32_t *') -> "void":
        return _mmu.inPort_copy(self, data)

    def __init__(self):
        this = _mmu.new_inPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_inPort
    __del__ = lambda self: None
inPort_swigregister = _mmu.inPort_swigregister
inPort_swigregister(inPort)

class outPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, outPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, outPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["port"] = _mmu.outPort_port_set
    __swig_getmethods__["port"] = _mmu.outPort_port_get
    if _newclass:
        port = _swig_property(_mmu.outPort_port_get, _mmu.outPort_port_set)
    __swig_setmethods__["data"] = _mmu.outPort_data_set
    __swig_getmethods__["data"] = _mmu.outPort_data_get
    if _newclass:
        data = _swig_property(_mmu.outPort_data_get, _mmu.outPort_data_set)
    __swig_setmethods__["ioId"] = _mmu.outPort_ioId_set
    __swig_getmethods__["ioId"] = _mmu.outPort_ioId_get
    if _newclass:
        ioId = _swig_property(_mmu.outPort_ioId_get, _mmu.outPort_ioId_set)
    __swig_setmethods__["comp"] = _mmu.outPort_comp_set
    __swig_getmethods__["comp"] = _mmu.outPort_comp_get
    if _newclass:
        comp = _swig_property(_mmu.outPort_comp_get, _mmu.outPort_comp_set)
    __swig_setmethods__["targetIoId"] = _mmu.outPort_targetIoId_set
    __swig_getmethods__["targetIoId"] = _mmu.outPort_targetIoId_get
    if _newclass:
        targetIoId = _swig_property(_mmu.outPort_targetIoId_get, _mmu.outPort_targetIoId_set)
    __swig_setmethods__["targetComp"] = _mmu.outPort_targetComp_set
    __swig_getmethods__["targetComp"] = _mmu.outPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_mmu.outPort_targetComp_get, _mmu.outPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _mmu.outPort_targetEval_set
    __swig_getmethods__["targetEval"] = _mmu.outPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_mmu.outPort_targetEval_get, _mmu.outPort_targetEval_set)
    __swig_setmethods__["updated"] = _mmu.outPort_updated_set
    __swig_getmethods__["updated"] = _mmu.outPort_updated_get
    if _newclass:
        updated = _swig_property(_mmu.outPort_updated_get, _mmu.outPort_updated_set)

    def checkTarget(self) -> "void":
        return _mmu.outPort_checkTarget(self)

    def write32(self, value: 'uint32_t') -> "void":
        return _mmu.outPort_write32(self, value)

    def __init__(self):
        this = _mmu.new_outPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_outPort
    __del__ = lambda self: None
outPort_swigregister = _mmu.outPort_swigregister
outPort_swigregister(outPort)

class combRegInit(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, combRegInit, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, combRegInit, name)
    __repr__ = _swig_repr

    def __init__(self, port: 'outPort', data: 'uint32_t *'):
        this = _mmu.new_combRegInit(port, data)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["port"] = _mmu.combRegInit_port_set
    __swig_getmethods__["port"] = _mmu.combRegInit_port_get
    if _newclass:
        port = _swig_property(_mmu.combRegInit_port_get, _mmu.combRegInit_port_set)
    __swig_setmethods__["data"] = _mmu.combRegInit_data_set
    __swig_getmethods__["data"] = _mmu.combRegInit_data_get
    if _newclass:
        data = _swig_property(_mmu.combRegInit_data_get, _mmu.combRegInit_data_set)
    __swig_destroy__ = _mmu.delete_combRegInit
    __del__ = lambda self: None
combRegInit_swigregister = _mmu.combRegInit_swigregister
combRegInit_swigregister(combRegInit)

class component(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, component, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, component, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mmu.new_component()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def setEngine(self, engineInstance: 'unsigned long') -> "void":
        return _mmu.component_setEngine(self, engineInstance)

    def build(self) -> "int":
        return _mmu.component_build(self)

    def start(self) -> "int":
        return _mmu.component_start(self)

    def reset(self) -> "void":
        return _mmu.component_reset(self)

    def close(self) -> "void":
        return _mmu.component_close(self)
    __swig_destroy__ = _mmu.delete_component
    __del__ = lambda self: None

    def state(self, name: 'char *') -> "void":
        return _mmu.component_state(self, name)

    def memDump(self, base: 'unsigned int', size: 'unsigned int') -> "bool":
        return _mmu.component_memDump(self, base, size)

    def getCycles(self) -> "int64_t":
        return _mmu.component_getCycles(self)

    def disAllBkp(self) -> "void":
        return _mmu.component_disAllBkp(self)

    def setBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int') -> "void":
        return _mmu.component_setBkp(self, base, size, access)

    def checkBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int', matchAddr: 'unsigned int &', matchAccess: 'unsigned int &') -> "bool":
        return _mmu.component_checkBkp(self, base, size, access, matchAddr, matchAccess)

    def reg(self, outPort: 'outPort', data: 'uint32_t *', localData: 'uint32_t **', inPort: 'inPort') -> "void":
        return _mmu.component_reg(self, outPort, data, localData, inPort)

    def regOut(self, name: 'string', port: 'outPort') -> "void":
        return _mmu.component_regOut(self, name, port)

    def regIn(self, *args) -> "void":
        return _mmu.component_regIn(self, *args)

    def evalNetwork(self) -> "void":
        return _mmu.component_evalNetwork(self)

    def commitNetwork(self) -> "void":
        return _mmu.component_commitNetwork(self)

    def setNetwork(self, network: 'component') -> "void":
        return _mmu.component_setNetwork(self, network)

    def eval(self) -> "void":
        return _mmu.component_eval(self)

    def precommit(self) -> "void":
        return _mmu.component_precommit(self)

    def commit(self) -> "void":
        return _mmu.component_commit(self)

    def syncNextCycle(self, *args) -> "void":
        return _mmu.component_syncNextCycle(self, *args)

    def syncOut(self, *args) -> "void":
        return _mmu.component_syncOut(self, *args)

    def addCell(self, comp: 'component') -> "void":
        return _mmu.component_addCell(self, comp)

    def connectNetworkOutputs(self) -> "void":
        return _mmu.component_connectNetworkOutputs(self)

    def regSlave(self, name: 'string', port: 'slavePort') -> "void":
        return _mmu.component_regSlave(self, name, port)

    def registerPowerTrace(self, trace: 'gv::powerTrace **', name: 'char *') -> "bool":
        return _mmu.component_registerPowerTrace(self, trace, name)

    def confPowerTrace(self, trace: 'gv::powerTrace *') -> "void":
        return _mmu.component_confPowerTrace(self, trace)

    def confVcdTrace(self, trace: 'gv::vcdTrace *', path: 'char const *', isActive: 'bool', file: 'long') -> "void":
        return _mmu.component_confVcdTrace(self, trace, path, isActive, file)

    def getSlavePort(self, name: 'char *') -> "gv::slavePort *":
        return _mmu.component_getSlavePort(self, name)

    def getSlavePortResync(self, initiatorEngine: 'unsigned long long', port: 'slavePort') -> "gv::slavePort *":
        return _mmu.component_getSlavePortResync(self, initiatorEngine, port)

    def regMaster(self, name: 'string', port: 'gv::masterPort *') -> "void":
        return _mmu.component_regMaster(self, name, port)

    def getMasterName(self, index: 'unsigned int') -> "char const *":
        return _mmu.component_getMasterName(self, index)

    def getSlaveName(self, index: 'unsigned int') -> "char const *":
        return _mmu.component_getSlaveName(self, index)

    def getTrace(self, name: 'char const *') -> "gv::trace *":
        return _mmu.component_getTrace(self, name)

    def getVcdTrace(self, name: 'char const *') -> "gv::vcdTrace *":
        return _mmu.component_getVcdTrace(self, name)

    def getTraceName(self, index: 'unsigned int') -> "char const *":
        return _mmu.component_getTraceName(self, index)

    def getVcdTraceName(self, index: 'unsigned int') -> "char const *":
        return _mmu.component_getVcdTraceName(self, index)

    def linkMasterTo(self, name: 'char const *', slavePort: 'slavePort') -> "void":
        return _mmu.component_linkMasterTo(self, name, slavePort)

    def regTrace(self, name: 'string', tr: 'trace') -> "void":
        return _mmu.component_regTrace(self, name, tr)

    def regVcd(self, name: 'string', vcd: 'gv::vcdTrace *', width: 'int') -> "void":
        return _mmu.component_regVcd(self, name, vcd, width)

    def regVcdString(self, name: 'string', vcd: 'gv::vcdTrace *') -> "void":
        return _mmu.component_regVcdString(self, name, vcd)

    def getUserTrace(self) -> "gv::trace *":
        return _mmu.component_getUserTrace(self)

    def getEngine(self) -> "engine *":
        return _mmu.component_getEngine(self)

    def getPowerEngine(self) -> "gv::powerEngine *":
        return _mmu.component_getPowerEngine(self)

    def confTrace(self, name: 'char const *', path: 'char const *', active: 'bool') -> "void":
        return _mmu.component_confTrace(self, name, path, active)

    def reorderCell(self, nextComp: 'component') -> "void":
        return _mmu.component_reorderCell(self, nextComp)

    def dequeueCell(self) -> "void":
        return _mmu.component_dequeueCell(self)
    __swig_setmethods__["network"] = _mmu.component_network_set
    __swig_getmethods__["network"] = _mmu.component_network_get
    if _newclass:
        network = _swig_property(_mmu.component_network_get, _mmu.component_network_set)
    __swig_setmethods__["evaluated"] = _mmu.component_evaluated_set
    __swig_getmethods__["evaluated"] = _mmu.component_evaluated_get
    if _newclass:
        evaluated = _swig_property(_mmu.component_evaluated_get, _mmu.component_evaluated_set)
    __swig_setmethods__["path"] = _mmu.component_path_set
    __swig_getmethods__["path"] = _mmu.component_path_get
    if _newclass:
        path = _swig_property(_mmu.component_path_get, _mmu.component_path_set)
    __swig_setmethods__["evalCell"] = _mmu.component_evalCell_set
    __swig_getmethods__["evalCell"] = _mmu.component_evalCell_get
    if _newclass:
        evalCell = _swig_property(_mmu.component_evalCell_get, _mmu.component_evalCell_set)
component_swigregister = _mmu.component_swigregister
component_swigregister(component)

class callback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callback, name)
    __repr__ = _swig_repr

    def __init__(self, handler: 'gv::callback_handle'):
        this = _mmu.new_callback(handler)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def _exec(self) -> "void":
        return _mmu.callback__exec(self)
    __swig_destroy__ = _mmu.delete_callback
    __del__ = lambda self: None
callback_swigregister = _mmu.callback_swigregister
callback_swigregister(callback)

class callbackFifo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callbackFifo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callbackFifo, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mmu.new_callbackFifo()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push(self, callback: 'callback') -> "void":
        return _mmu.callbackFifo_push(self, callback)

    def pop(self) -> "gv::callback *":
        return _mmu.callbackFifo_pop(self)

    def popAndExec(self) -> "void":
        return _mmu.callbackFifo_popAndExec(self)
    __swig_destroy__ = _mmu.delete_callbackFifo
    __del__ = lambda self: None
callbackFifo_swigregister = _mmu.callbackFifo_swigregister
callbackFifo_swigregister(callbackFifo)


_mmu.GV_IOREQ_ERROR_swigconstant(_mmu)
GV_IOREQ_ERROR = _mmu.GV_IOREQ_ERROR

_mmu.GV_IOREQ_STALLED_swigconstant(_mmu)
GV_IOREQ_STALLED = _mmu.GV_IOREQ_STALLED

_mmu.GV_IOREQ_NB_STALL_DATA_swigconstant(_mmu)
GV_IOREQ_NB_STALL_DATA = _mmu.GV_IOREQ_NB_STALL_DATA
class ioReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ioReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', addr: 'uint32_t', data: 'uint8_t *', size: 'uint32_t', isRead: 'bool'):
        this = _mmu.new_ioReq(initiator, addr, data, size, isRead)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def getAddr(self) -> "uint32_t":
        return _mmu.ioReq_getAddr(self)

    def setAddr(self, addr: 'uint32_t') -> "void":
        return _mmu.ioReq_setAddr(self, addr)

    def getData(self) -> "uint8_t *":
        return _mmu.ioReq_getData(self)

    def setData(self, data: 'uint8_t *') -> "void":
        return _mmu.ioReq_setData(self, data)

    def getSize(self) -> "uint32_t":
        return _mmu.ioReq_getSize(self)

    def setSize(self, size: 'uint32_t') -> "void":
        return _mmu.ioReq_setSize(self, size)

    def getIsRead(self) -> "bool":
        return _mmu.ioReq_getIsRead(self)

    def setIsRead(self, isRead: 'bool') -> "void":
        return _mmu.ioReq_setIsRead(self, isRead)

    def setLatency(self, newLatency: 'int64_t') -> "void":
        return _mmu.ioReq_setLatency(self, newLatency)

    def incLatency(self, incr: 'int64_t') -> "void":
        return _mmu.ioReq_incLatency(self, incr)

    def setLength(self, newDuration: 'int64_t') -> "void":
        return _mmu.ioReq_setLength(self, newDuration)

    def getStartCycles(self) -> "int64_t":
        return _mmu.ioReq_getStartCycles(self)

    def getLatency(self) -> "int64_t":
        return _mmu.ioReq_getLatency(self)

    def getLength(self) -> "int64_t":
        return _mmu.ioReq_getLength(self)

    def getEndCycles(self) -> "int64_t":
        return _mmu.ioReq_getEndCycles(self)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _mmu.ioReq_switchEngine(self, engine)

    def getEngine(self) -> "engine *":
        return _mmu.ioReq_getEngine(self)

    def setDebug(self, value: 'bool') -> "void":
        return _mmu.ioReq_setDebug(self, value)

    def getDebug(self) -> "bool":
        return _mmu.ioReq_getDebug(self)

    def setSecure(self, value: 'bool') -> "void":
        return _mmu.ioReq_setSecure(self, value)

    def getSecure(self) -> "bool":
        return _mmu.ioReq_getSecure(self)
    __swig_setmethods__["error"] = _mmu.ioReq_error_set
    __swig_getmethods__["error"] = _mmu.ioReq_error_get
    if _newclass:
        error = _swig_property(_mmu.ioReq_error_get, _mmu.ioReq_error_set)
    __swig_setmethods__["stallCallback"] = _mmu.ioReq_stallCallback_set
    __swig_getmethods__["stallCallback"] = _mmu.ioReq_stallCallback_get
    if _newclass:
        stallCallback = _swig_property(_mmu.ioReq_stallCallback_get, _mmu.ioReq_stallCallback_set)
    __swig_setmethods__["stallRetryCallback"] = _mmu.ioReq_stallRetryCallback_set
    __swig_getmethods__["stallRetryCallback"] = _mmu.ioReq_stallRetryCallback_get
    if _newclass:
        stallRetryCallback = _swig_property(_mmu.ioReq_stallRetryCallback_get, _mmu.ioReq_stallRetryCallback_set)
    __swig_setmethods__["stallData"] = _mmu.ioReq_stallData_set
    __swig_getmethods__["stallData"] = _mmu.ioReq_stallData_get
    if _newclass:
        stallData = _swig_property(_mmu.ioReq_stallData_get, _mmu.ioReq_stallData_set)
    __swig_setmethods__["next"] = _mmu.ioReq_next_set
    __swig_getmethods__["next"] = _mmu.ioReq_next_get
    if _newclass:
        next = _swig_property(_mmu.ioReq_next_get, _mmu.ioReq_next_set)
    __swig_destroy__ = _mmu.delete_ioReq
    __del__ = lambda self: None
ioReq_swigregister = _mmu.ioReq_swigregister
ioReq_swigregister(ioReq)

class ioSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ioSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_ioSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["ioReq"] = _mmu.ioSlave_ioReq_set
    __swig_getmethods__["ioReq"] = _mmu.ioSlave_ioReq_get
    if _newclass:
        ioReq = _swig_property(_mmu.ioSlave_ioReq_get, _mmu.ioSlave_ioReq_set)
    __swig_setmethods__["resyncTarget"] = _mmu.ioSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.ioSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.ioSlave_resyncTarget_get, _mmu.ioSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.ioSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.ioSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.ioSlave_initiatorEngine_get, _mmu.ioSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.ioSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.ioSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.ioSlave_targetEngine_get, _mmu.ioSlave_targetEngine_set)

    def ioReqResync(self, req: 'ioReq') -> "bool":
        return _mmu.ioSlave_ioReqResync(self, req)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.ioSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_ioSlave
    __del__ = lambda self: None
ioSlave_swigregister = _mmu.ioSlave_swigregister
ioSlave_swigregister(ioSlave)

class combSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, combSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, combSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_combSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regMeth"] = _mmu.combSlave_regMeth_set
    __swig_getmethods__["regMeth"] = _mmu.combSlave_regMeth_get
    if _newclass:
        regMeth = _swig_property(_mmu.combSlave_regMeth_get, _mmu.combSlave_regMeth_set)
    __swig_setmethods__["resyncTarget"] = _mmu.combSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.combSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.combSlave_resyncTarget_get, _mmu.combSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.combSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.combSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.combSlave_initiatorEngine_get, _mmu.combSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.combSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.combSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.combSlave_targetEngine_get, _mmu.combSlave_targetEngine_set)

    def regResync(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _mmu.combSlave_regResync(self, outPort, data)

    def reg(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _mmu.combSlave_reg(self, outPort, data)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.combSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_combSlave
    __del__ = lambda self: None
combSlave_swigregister = _mmu.combSlave_swigregister
combSlave_swigregister(combSlave)

class bsReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bsReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', headerSize: 'int', dataSize: 'int', dataLen: 'int'=0):
        this = _mmu.new_bsReq(initiator, headerSize, dataSize, dataLen)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_bsReq
    __del__ = lambda self: None

    def getIsRead(self) -> "bool":
        return _mmu.bsReq_getIsRead(self)

    def getData(self) -> "uint8_t *":
        return _mmu.bsReq_getData(self)

    def getDataHead(self) -> "int":
        return _mmu.bsReq_getDataHead(self)

    def setDataHead(self, head: 'int') -> "void":
        return _mmu.bsReq_setDataHead(self, head)

    def getHeader(self) -> "uint8_t *":
        return _mmu.bsReq_getHeader(self)

    def setNext(self, req: 'bsReq') -> "void":
        return _mmu.bsReq_setNext(self, req)

    def getNext(self) -> "gv::bsReq *":
        return _mmu.bsReq_getNext(self)

    def getDataSize(self) -> "int":
        return _mmu.bsReq_getDataSize(self)

    def getDataLen(self) -> "int":
        return _mmu.bsReq_getDataLen(self)

    def setLatency(self, latency: 'int64_t') -> "void":
        return _mmu.bsReq_setLatency(self, latency)

    def getLatency(self) -> "int64_t":
        return _mmu.bsReq_getLatency(self)

    def setDataSize(self, _dataSize: 'int') -> "void":
        return _mmu.bsReq_setDataSize(self, _dataSize)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _mmu.bsReq_switchEngine(self, engine)
bsReq_swigregister = _mmu.bsReq_swigregister
bsReq_swigregister(bsReq)

class bsSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, bsSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_bsSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["bsReqMeth"] = _mmu.bsSlave_bsReqMeth_set
    __swig_getmethods__["bsReqMeth"] = _mmu.bsSlave_bsReqMeth_get
    if _newclass:
        bsReqMeth = _swig_property(_mmu.bsSlave_bsReqMeth_get, _mmu.bsSlave_bsReqMeth_set)
    __swig_setmethods__["bsDataMeth"] = _mmu.bsSlave_bsDataMeth_set
    __swig_getmethods__["bsDataMeth"] = _mmu.bsSlave_bsDataMeth_get
    if _newclass:
        bsDataMeth = _swig_property(_mmu.bsSlave_bsDataMeth_get, _mmu.bsSlave_bsDataMeth_set)
    __swig_setmethods__["resyncTarget"] = _mmu.bsSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.bsSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.bsSlave_resyncTarget_get, _mmu.bsSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.bsSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.bsSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.bsSlave_initiatorEngine_get, _mmu.bsSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.bsSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.bsSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.bsSlave_targetEngine_get, _mmu.bsSlave_targetEngine_set)

    def bsReqResync(self, req: 'bsReq') -> "bool":
        return _mmu.bsSlave_bsReqResync(self, req)

    def bsDataResync(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _mmu.bsSlave_bsDataResync(self, data, dataLen, latency)

    def bsReq(self, req: 'bsReq') -> "bool":
        return _mmu.bsSlave_bsReq(self, req)

    def bsData(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _mmu.bsSlave_bsData(self, data, dataLen, latency)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.bsSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_bsSlave
    __del__ = lambda self: None
bsSlave_swigregister = _mmu.bsSlave_swigregister
bsSlave_swigregister(bsSlave)

class spiHeader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, spiHeader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, spiHeader, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cmd"] = _mmu.spiHeader_cmd_set
    __swig_getmethods__["cmd"] = _mmu.spiHeader_cmd_get
    if _newclass:
        cmd = _swig_property(_mmu.spiHeader_cmd_get, _mmu.spiHeader_cmd_set)
    __swig_setmethods__["addr"] = _mmu.spiHeader_addr_set
    __swig_getmethods__["addr"] = _mmu.spiHeader_addr_get
    if _newclass:
        addr = _swig_property(_mmu.spiHeader_addr_get, _mmu.spiHeader_addr_set)
    __swig_setmethods__["len"] = _mmu.spiHeader_len_set
    __swig_getmethods__["len"] = _mmu.spiHeader_len_get
    if _newclass:
        len = _swig_property(_mmu.spiHeader_len_get, _mmu.spiHeader_len_set)
    __swig_setmethods__["cs"] = _mmu.spiHeader_cs_set
    __swig_getmethods__["cs"] = _mmu.spiHeader_cs_get
    if _newclass:
        cs = _swig_property(_mmu.spiHeader_cs_get, _mmu.spiHeader_cs_set)

    def __init__(self):
        this = _mmu.new_spiHeader()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_spiHeader
    __del__ = lambda self: None
spiHeader_swigregister = _mmu.spiHeader_swigregister
spiHeader_swigregister(spiHeader)

class wireSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, wireSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, wireSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_wireSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["syncMeth"] = _mmu.wireSlave_syncMeth_set
    __swig_getmethods__["syncMeth"] = _mmu.wireSlave_syncMeth_get
    if _newclass:
        syncMeth = _swig_property(_mmu.wireSlave_syncMeth_get, _mmu.wireSlave_syncMeth_set)
    __swig_setmethods__["resyncTarget"] = _mmu.wireSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.wireSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.wireSlave_resyncTarget_get, _mmu.wireSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.wireSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.wireSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.wireSlave_initiatorEngine_get, _mmu.wireSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.wireSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.wireSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.wireSlave_targetEngine_get, _mmu.wireSlave_targetEngine_set)

    def syncResync(self, value: 'uint32_t') -> "void":
        return _mmu.wireSlave_syncResync(self, value)

    def sync(self, value: 'uint32_t') -> "void":
        return _mmu.wireSlave_sync(self, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.wireSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_wireSlave
    __del__ = lambda self: None
wireSlave_swigregister = _mmu.wireSlave_swigregister
wireSlave_swigregister(wireSlave)

class cpuCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cpuCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cpuCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_cpuCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccess"] = _mmu.cpuCtrlSlave_regAccess_set
    __swig_getmethods__["regAccess"] = _mmu.cpuCtrlSlave_regAccess_get
    if _newclass:
        regAccess = _swig_property(_mmu.cpuCtrlSlave_regAccess_get, _mmu.cpuCtrlSlave_regAccess_set)
    __swig_setmethods__["resyncTarget"] = _mmu.cpuCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.cpuCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.cpuCtrlSlave_resyncTarget_get, _mmu.cpuCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.cpuCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.cpuCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.cpuCtrlSlave_initiatorEngine_get, _mmu.cpuCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.cpuCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.cpuCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.cpuCtrlSlave_targetEngine_get, _mmu.cpuCtrlSlave_targetEngine_set)

    def regAccessResync(self, reg: 'uint32_t', isRead: 'int', value: 'uint32_t *') -> "bool":
        return _mmu.cpuCtrlSlave_regAccessResync(self, reg, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.cpuCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_cpuCtrlSlave
    __del__ = lambda self: None
cpuCtrlSlave_swigregister = _mmu.cpuCtrlSlave_swigregister
cpuCtrlSlave_swigregister(cpuCtrlSlave)

class cacheCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cacheCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cacheCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_cacheCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["enable"] = _mmu.cacheCtrlSlave_enable_set
    __swig_getmethods__["enable"] = _mmu.cacheCtrlSlave_enable_get
    if _newclass:
        enable = _swig_property(_mmu.cacheCtrlSlave_enable_get, _mmu.cacheCtrlSlave_enable_set)
    __swig_setmethods__["flushAll"] = _mmu.cacheCtrlSlave_flushAll_set
    __swig_getmethods__["flushAll"] = _mmu.cacheCtrlSlave_flushAll_get
    if _newclass:
        flushAll = _swig_property(_mmu.cacheCtrlSlave_flushAll_get, _mmu.cacheCtrlSlave_flushAll_set)
    __swig_setmethods__["flushLine"] = _mmu.cacheCtrlSlave_flushLine_set
    __swig_getmethods__["flushLine"] = _mmu.cacheCtrlSlave_flushLine_get
    if _newclass:
        flushLine = _swig_property(_mmu.cacheCtrlSlave_flushLine_get, _mmu.cacheCtrlSlave_flushLine_set)
    __swig_setmethods__["resyncTarget"] = _mmu.cacheCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.cacheCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.cacheCtrlSlave_resyncTarget_get, _mmu.cacheCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.cacheCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.cacheCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.cacheCtrlSlave_initiatorEngine_get, _mmu.cacheCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.cacheCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.cacheCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.cacheCtrlSlave_targetEngine_get, _mmu.cacheCtrlSlave_targetEngine_set)

    def enableResync(self, enable: 'bool') -> "void":
        return _mmu.cacheCtrlSlave_enableResync(self, enable)

    def flushAllResync(self) -> "void":
        return _mmu.cacheCtrlSlave_flushAllResync(self)

    def flushLineResync(self, addr: 'unsigned int') -> "void":
        return _mmu.cacheCtrlSlave_flushLineResync(self, addr)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.cacheCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_cacheCtrlSlave
    __del__ = lambda self: None
cacheCtrlSlave_swigregister = _mmu.cacheCtrlSlave_swigregister
cacheCtrlSlave_swigregister(cacheCtrlSlave)

class regSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, regSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, regSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _mmu.new_regSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccessMeth"] = _mmu.regSlave_regAccessMeth_set
    __swig_getmethods__["regAccessMeth"] = _mmu.regSlave_regAccessMeth_get
    if _newclass:
        regAccessMeth = _swig_property(_mmu.regSlave_regAccessMeth_get, _mmu.regSlave_regAccessMeth_set)
    __swig_setmethods__["resyncTarget"] = _mmu.regSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _mmu.regSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_mmu.regSlave_resyncTarget_get, _mmu.regSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _mmu.regSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _mmu.regSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_mmu.regSlave_initiatorEngine_get, _mmu.regSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _mmu.regSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _mmu.regSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_mmu.regSlave_targetEngine_get, _mmu.regSlave_targetEngine_set)

    def regAccessResync(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _mmu.regSlave_regAccessResync(self, slaveId, isRead, value)

    def regAccess(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _mmu.regSlave_regAccess(self, slaveId, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _mmu.regSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _mmu.delete_regSlave
    __del__ = lambda self: None
regSlave_swigregister = _mmu.regSlave_swigregister
regSlave_swigregister(regSlave)


_mmu.kMiss_swigconstant(_mmu)
kMiss = _mmu.kMiss

_mmu.kHit_swigconstant(_mmu)
kHit = _mmu.kHit
class Pte(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pte, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pte, name)
    __repr__ = _swig_repr
    __swig_setmethods__["valid"] = _mmu.Pte_valid_set
    __swig_getmethods__["valid"] = _mmu.Pte_valid_get
    if _newclass:
        valid = _swig_property(_mmu.Pte_valid_get, _mmu.Pte_valid_set)
    __swig_setmethods__["read"] = _mmu.Pte_read_set
    __swig_getmethods__["read"] = _mmu.Pte_read_get
    if _newclass:
        read = _swig_property(_mmu.Pte_read_get, _mmu.Pte_read_set)
    __swig_setmethods__["write"] = _mmu.Pte_write_set
    __swig_getmethods__["write"] = _mmu.Pte_write_get
    if _newclass:
        write = _swig_property(_mmu.Pte_write_get, _mmu.Pte_write_set)
    __swig_setmethods__["execute"] = _mmu.Pte_execute_set
    __swig_getmethods__["execute"] = _mmu.Pte_execute_get
    if _newclass:
        execute = _swig_property(_mmu.Pte_execute_get, _mmu.Pte_execute_set)
    __swig_setmethods__["user"] = _mmu.Pte_user_set
    __swig_getmethods__["user"] = _mmu.Pte_user_get
    if _newclass:
        user = _swig_property(_mmu.Pte_user_get, _mmu.Pte_user_set)
    __swig_setmethods__["_global"] = _mmu.Pte__global_set
    __swig_getmethods__["_global"] = _mmu.Pte__global_get
    if _newclass:
        _global = _swig_property(_mmu.Pte__global_get, _mmu.Pte__global_set)
    __swig_setmethods__["accessed"] = _mmu.Pte_accessed_set
    __swig_getmethods__["accessed"] = _mmu.Pte_accessed_get
    if _newclass:
        accessed = _swig_property(_mmu.Pte_accessed_get, _mmu.Pte_accessed_set)
    __swig_setmethods__["dirty"] = _mmu.Pte_dirty_set
    __swig_getmethods__["dirty"] = _mmu.Pte_dirty_get
    if _newclass:
        dirty = _swig_property(_mmu.Pte_dirty_get, _mmu.Pte_dirty_set)
    __swig_setmethods__["sw"] = _mmu.Pte_sw_set
    __swig_getmethods__["sw"] = _mmu.Pte_sw_get
    if _newclass:
        sw = _swig_property(_mmu.Pte_sw_get, _mmu.Pte_sw_set)
    __swig_setmethods__["ppn"] = _mmu.Pte_ppn_set
    __swig_getmethods__["ppn"] = _mmu.Pte_ppn_get
    if _newclass:
        ppn = _swig_property(_mmu.Pte_ppn_get, _mmu.Pte_ppn_set)

    def __init__(self):
        this = _mmu.new_Pte()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_Pte
    __del__ = lambda self: None
Pte_swigregister = _mmu.Pte_swigregister
Pte_swigregister(Pte)

class LookupResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LookupResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LookupResult, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pte"] = _mmu.LookupResult_pte_set
    __swig_getmethods__["pte"] = _mmu.LookupResult_pte_get
    if _newclass:
        pte = _swig_property(_mmu.LookupResult_pte_get, _mmu.LookupResult_pte_set)
    __swig_setmethods__["pt_lvl"] = _mmu.LookupResult_pt_lvl_set
    __swig_getmethods__["pt_lvl"] = _mmu.LookupResult_pt_lvl_get
    if _newclass:
        pt_lvl = _swig_property(_mmu.LookupResult_pt_lvl_get, _mmu.LookupResult_pt_lvl_set)
    __swig_setmethods__["status"] = _mmu.LookupResult_status_set
    __swig_getmethods__["status"] = _mmu.LookupResult_status_get
    if _newclass:
        status = _swig_property(_mmu.LookupResult_status_get, _mmu.LookupResult_status_set)

    def __init__(self):
        this = _mmu.new_LookupResult()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_LookupResult
    __del__ = lambda self: None
LookupResult_swigregister = _mmu.LookupResult_swigregister
LookupResult_swigregister(LookupResult)

class Tlb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Tlb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Tlb, name)
    __repr__ = _swig_repr

    def flush(self, asid: 'uint32_t', vaddr: 'uint32_t') -> "void":
        return _mmu.Tlb_flush(self, asid, vaddr)

    def insertEntry(self, asid: 'uint32_t', vaddr: 'uint32_t', entry: 'Pte', pt_lvl: 'int8_t') -> "bool":
        return _mmu.Tlb_insertEntry(self, asid, vaddr, entry, pt_lvl)

    def lookupPTE(self, asid: 'uint32_t', vaddr: 'uint32_t', read0_write1: 'bool') -> "LookupResult":
        return _mmu.Tlb_lookupPTE(self, asid, vaddr, read0_write1)

    def __init__(self):
        this = _mmu.new_Tlb()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_Tlb
    __del__ = lambda self: None
Tlb_swigregister = _mmu.Tlb_swigregister
Tlb_swigregister(Tlb)

class Mmu(component):
    __swig_setmethods__ = {}
    for _s in [component]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mmu, name, value)
    __swig_getmethods__ = {}
    for _s in [component]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Mmu, name)
    __repr__ = _swig_repr

    def build(self) -> "int":
        return _mmu.Mmu_build(self)

    def start(self) -> "int":
        return _mmu.Mmu_start(self)
    __swig_setmethods__["dummyParam"] = _mmu.Mmu_dummyParam_set
    __swig_getmethods__["dummyParam"] = _mmu.Mmu_dummyParam_get
    if _newclass:
        dummyParam = _swig_property(_mmu.Mmu_dummyParam_get, _mmu.Mmu_dummyParam_set)

    def __init__(self):
        this = _mmu.new_Mmu()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mmu.delete_Mmu
    __del__ = lambda self: None
Mmu_swigregister = _mmu.Mmu_swigregister
Mmu_swigregister(Mmu)

# This file is compatible with both classic and new-style classes.


