# 
# Synthesis run script generated by Vivado
# 


create_project -in_memory -part xc7z045ffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.cache/wt [current_project]
set_property parent.project_path /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:0.9 [current_project]
read_ip /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.xci
set_property is_locked true [get_files /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file xilinx_icache_bank_data_16x128.hwdef }
synth_design -top xilinx_icache_bank_data_16x128 -part xc7z045ffg900-2 -mode out_of_context
rename_ref -prefix_all xilinx_icache_bank_data_16x128_
write_checkpoint -noxdef xilinx_icache_bank_data_16x128.dcp
catch { report_utilization -file xilinx_icache_bank_data_16x128_utilization_synth.rpt -pb xilinx_icache_bank_data_16x128_utilization_synth.pb }
if { [catch {
  file copy -force /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.runs/xilinx_icache_bank_data_16x128_synth_1/xilinx_icache_bank_data_16x128.dcp /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/gianfranco/pulp/pulp4/fpga/ips/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128.srcs/sources_1/ip/xilinx_icache_bank_data_16x128/xilinx_icache_bank_data_16x128_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
