/******************************************************************************
 *          EOLAB @ DIEE - Università degli studi di Cagliari                 *
 *                      Via marengo 2 - 09123                                 *
 *                              Cagliari                                      *
 *                                                                            *
 *                 Gianfranco Deriu - gian.deriu@gmail.com                    *
 *                                                                            *
 * Project:        NURAGHE                                                    *
 * File:           default_setting.h                                          *
 * Description:    This file contains the default settings for the layer      *
 *                 to be simulated. These settings are ignored when           *
 *                 NURAGHE is programmed from ARM processor                   *
 *                                                                            *
 ******************************************************************************/
#ifndef _DEFAULT_SETTINGS
#define _DEFAULT_SETTINGS

//number of input features
#define default_IF              36
//number of output features
#define default_OF              40

//height of the input features
#define default_IH              30
//width of the input features
#define default_IW              30

//filter size
#define default_FS               3  

//dilation
#define default_DIL              1 

#if default_IH > 1
  #define default_FS_h  default_FS
  #define default_dil_h  default_DIL
#else
   #define default_FS_h          1
  #define default_dil_h          1
#endif

#if default_IW > 1
  #define default_FS_w  default_FS
  #define default_dil_w  default_DIL
#else
  #define default_FS_w           1 
  #define default_dil_w          1     
#endif  

//use hardware ReLu
#define default_rectifier_activ  0

//use hardware pooling     
// default_pooling_hw  [1]: window size: 0: 2x2; 1: 4x4  
// default_pooling_hw  [0]:              0: pool on 1: pool off 
// default_pooling_hw[3:2]: method      00: max; 01: avg; 10: downsampling 

#define default_pooling_hw      0b0000

//#define default_method_pooling  0b00

//use hardware zero-padding
#define default_zero_padding     1


//it must be choosed properly depending on output size and TCDM size
// NOTE: if you change MAX_OG you ought to re-run the post-training script because the weights arrangement depends on MAX_OG parameter.
#define default_MAX_OG          2

//qf
#define default_QF              4

#define default_precision8      0



//file generated by post-training scripts. this file is not used out of the simulation

//#define TEST_FILE           "tests/resnetConvLayer2/header.h"
#define TEST_FILE           "tests/fake_test/header.h"
//#define TEST_FILE           "tests/realtestL1/header.h"

#endif
