# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gderiu/marco/neuraghe_zc706_8_16_runtime_dma2d_lenhack/fpga/ips/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.srcs/sources_1/ip/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.xci
# IP: The module: 'xilinx_tcdm_bank_4096x16_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gderiu/marco/neuraghe_zc706_8_16_runtime_dma2d_lenhack/fpga/ips/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.srcs/sources_1/ip/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_tcdm_bank_4096x16_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/gderiu/marco/neuraghe_zc706_8_16_runtime_dma2d_lenhack/fpga/ips/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.srcs/sources_1/ip/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.xci
# IP: The module: 'xilinx_tcdm_bank_4096x16_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gderiu/marco/neuraghe_zc706_8_16_runtime_dma2d_lenhack/fpga/ips/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16.srcs/sources_1/ip/xilinx_tcdm_bank_4096x16_16/xilinx_tcdm_bank_4096x16_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_tcdm_bank_4096x16_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
