onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {CORE 3 REGION}
add wave -noupdate /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/cluster_int_region_i/cluster_interconnect_wrap_i/clk_i
add wave -noupdate /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/cluster_int_region_i/cluster_interconnect_wrap_i/rst_ni
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/clk_i}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/rst_ni}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/init_ni}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/cluster_id_i}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/fetch_en_i}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/test_mode_i}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/ic_en}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/ic_addr}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_we}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/to_icram}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_dataout_even}
add wave -noupdate {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_dataout_odd}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/req}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/add}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/we}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/wdata}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/be}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/gnt}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/r_opc}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/r_rdata}
add wave -noupdate -group CORE_3_TCDM_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/tcdm_data_master/r_valid}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/req}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/add}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/we}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/wdata}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/be}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/gnt}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/r_opc}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/r_rdata}
add wave -noupdate -group CORE_3_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/dma_ctrl_master/r_valid}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/req}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/add}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/we}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/wdata}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/be}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/gnt}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/id}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/r_valid}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/r_opc}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/r_id}
add wave -noupdate -group CORE_3_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/periph_data_master/r_rdata}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_addr}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_prot}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_region}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_len}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_size}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_burst}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_lock}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_cache}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_qos}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_id}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_user}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_ready}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/aw_valid}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_addr}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_prot}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_region}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_len}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_size}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_burst}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_lock}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_cache}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_qos}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_id}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_user}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_ready}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/ar_valid}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_valid}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_data}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_strb}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_user}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_last}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/w_ready}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_data}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_resp}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_last}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_id}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_user}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_ready}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/r_valid}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/b_resp}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/b_id}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/b_user}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/b_ready}
add wave -noupdate -group CORE_3_CORE_INSTR_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_instr_master/b_valid}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_en}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_done_even}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_done_odd}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_result_even}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_result_odd}
add wave -noupdate -group CORE_3_S_ICRAM_BIST {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/icram_bist_slave/bist_pattern}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/adr}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/data}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/sel}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/we}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/cyc}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/stb}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/cti}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/bte}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/rdata}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/ack}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/err}
add wave -noupdate -group CORE_3_S_IBUS_WB {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_ibus_wb/rty}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/barrier}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/busy}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/exec_cancel}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/exec_stall}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/req}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/add}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/we}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/wdata}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/be}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/gnt}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/r_gnt}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/r_valid}
add wave -noupdate -group CORE_3_S_CORE_BUS {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/s_core_bus/r_rdata}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/clk_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/rst_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/init_ni}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/clmode_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pic_ints_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/fetch_en_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_clk_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_rst_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_ack_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_err_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_rty_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_dat_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_cyc_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_adr_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_stb_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_we_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_sel_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_dat_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_cti_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/iwb_bte_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_clk_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_rst_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_ack_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_err_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_rty_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_dat_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_cyc_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_adr_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_stb_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_we_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_sel_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_dat_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_cti_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dwb_bte_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_req_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_add_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_type_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_wdata_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_be_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_gnt_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_r_valid_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_r_opc_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/lint_r_rdata_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ic_en_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ic_addr_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icram_we_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/to_icram_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icram_dataout_even_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icram_dataout_odd_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_stall_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_ewt_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_lss_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_is_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_wp_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_bp_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_stb_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_we_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_adr_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_dat_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_dat_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dbg_ack_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_cpustall_i}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_clksd_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_dc_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_ic_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_dmmu_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_immu_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_tt_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_cpu_gate_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_wakeup_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pm_lvolt_o}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_dat_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_adr_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_cyc_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_stb_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_we_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_sel_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_cab_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_dat_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_ack_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcsb_err_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_dat_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_adr_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_cyc_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_stb_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_we_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_sel_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_cab_sb}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_dat_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_ack_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sbbiu_err_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_dat_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_adr_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_adr_ic_word}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_cyc_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_stb_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_we_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_sel_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_tag_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_cab_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_dat_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_ack_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_err_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icbiu_tag_biu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/boot_adr_sel}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/supv}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_addr}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_cs}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_we}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/mtspr_dc_done}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sb_en}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dmmu_en}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemdmmu_err_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemdmmu_tag_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemdmmu_adr_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemdmmu_cycstb_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemdmmu_ci_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dc_en}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_adr_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_cycstb_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_we_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_sel_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_tag_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_dat_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_dat_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_ack_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_rty_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_err_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcpu_tag_dmmu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dc_no_writethrough}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/immu_en}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ic_en}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_adr_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_cycstb_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_sel_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_tag_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_dat_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_ack_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_adr_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_err_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_tag_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icpu_rty_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_adr_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_rty_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_err_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_tag_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_cycstb_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/qmemimmu_ci_immu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_adr_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_rty_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_err_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_tag_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_cycstb_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_ci_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_dat_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_ack_ic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_adr_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_rty_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_err_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_tag_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_cycstb_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_ci_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_dat_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_dat_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_we_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_sel_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_ack_dc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_pic}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/pic_wakeup}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sig_int}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_pm}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_tt}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/sig_tick}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_du}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_stall}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_addr}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_dat_du}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_read}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_write}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_except_trig}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_except_stop}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_dsr}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_dmr1}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_dat_cpu}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_lsu_store_dat}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_lsu_load_dat}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_hwbkpt}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/du_hwbkpt_ls_r}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/flushpipe}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ex_freeze}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/wb_freeze}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/id_void}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ex_void}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/id_insn}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ex_insn}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/wb_insn}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/id_pc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/ex_pc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/wb_pc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/branch_op}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/spr_dat_npc}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/rf_dataw}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/abort_ex}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/abort_mvspr}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_sel_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/icqmem_tag_qmem}
add wave -noupdate -group CORE_3_CPU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/or1200_top_i/dcqmem_tag_qmem}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/cluster_id_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/clk}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/rst_ni}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_req_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_add_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_type_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_wdata_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_be_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_gnt_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_busy_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/flush_pipe}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/stall_pipe}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_gnt_i}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_valid_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_rdata_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_opc_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/conflicts_counter_o}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_req_o_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_add_o_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_type_o_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_wdata_o_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_be_o_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_gnt_i_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_valid_i_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_rdata_i_SH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_req_o_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_add_o_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_type_o_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_wdata_o_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_be_o_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_gnt_i_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_valid_i_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_rdata_i_MH}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_busy_i_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_req_o_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_add_o_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_type_o_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_wdata_o_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_be_o_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_gnt_i_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_valid_i_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_opc_i_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/data_r_rdata_i_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_gnt_ID}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_opc_ID}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_valid_ID}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_rdata_ID}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_req_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_gnt_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_data_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_valid_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_opc_PE}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_data_PE_0}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_valid_PE_0}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_r_opc_PE_0}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_add_s}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_data_type_s}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/s_cluster_id}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/CS}
add wave -noupdate -group CORE_3_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_demux_i/NS}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/clk}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/rst}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/init_ni}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/addr_i}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/en_i}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/we_i}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/datain_i}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/dataout_even_o}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/dataout_odd_o}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/we_bist_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/re_bist_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/addr_bist_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/wdata_bist_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/rdata_bist_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/we_bist_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/re_bist_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/addr_bist_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/wdata_bist_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/rdata_bist_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/we_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/re_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/addr_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/wdata_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/rdata_even}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/we_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/re_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/addr_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/wdata_odd}
add wave -noupdate -group CORE_3_IC_RAM {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[3]/core_region_i/core_ic_ram_i/rdata_odd}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2175610000 ps} 0}
configure wave -namecolwidth 654
configure wave -valuecolwidth 118
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {8846103063 ps} {8938152471 ps}
