onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {CLUSTER BRIDGES}
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_addr
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_prot
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_region
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_len
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_size
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_burst
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_lock
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_cache
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_qos
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_id
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_user
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_ready
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/aw_valid
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_addr
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_prot
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_region
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_len
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_size
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_burst
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_lock
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_cache
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_qos
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_id
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_user
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_ready
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/ar_valid
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_valid
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_data
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_strb
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_user
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_last
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/w_ready
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_data
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_resp
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_last
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_id
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_user
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_ready
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/r_valid
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/b_resp
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/b_id
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/b_user
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/b_ready
add wave -noupdate -group {SOC BUS CLUSTER INSTR SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_instr_slave/b_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_addr
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_prot
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_region
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_len
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_size
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_burst
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_lock
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_cache
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_qos
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_id
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_user
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/aw_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_addr
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_prot
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_region
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_len
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_size
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_burst
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_lock
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_cache
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_qos
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_id
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_user
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/ar_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_data
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_strb
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_user
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_last
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/w_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_data
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_resp
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_last
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_id
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_user
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/r_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/b_resp
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/b_id
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/b_user
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/b_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_slave/b_valid
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_addr
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_prot
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_region
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_len
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_size
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_burst
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_lock
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_cache
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_qos
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_id
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_user
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_ready
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/aw_valid
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_addr
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_prot
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_region
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_len
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_size
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_burst
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_lock
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_cache
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_qos
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_id
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_user
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_ready
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/ar_valid
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_valid
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_data
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_strb
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_user
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_last
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/w_ready
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_data
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_resp
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_last
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_id
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_user
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_ready
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/r_valid
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/b_resp
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/b_id
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/b_user
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/b_ready
add wave -noupdate -group {SOC BUS SOC EXT SLAVE} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_slave/b_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_addr
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_prot
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_region
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_len
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_size
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_burst
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_lock
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_cache
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_qos
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_id
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_user
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/aw_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_addr
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_prot
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_region
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_len
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_size
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_burst
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_lock
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_cache
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_qos
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_id
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_user
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/ar_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_data
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_strb
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_user
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_last
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/w_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_data
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_resp
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_last
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_id
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_user
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/r_valid
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/b_resp
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/b_id
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/b_user
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/b_ready
add wave -noupdate -group {SOC BUS CLUSTER DATA MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/cluster_data_master/b_valid
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_addr
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_prot
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_region
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_len
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_size
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_burst
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_lock
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_cache
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_qos
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_id
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_user
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_ready
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/aw_valid
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_addr
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_prot
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_region
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_len
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_size
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_burst
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_lock
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_cache
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_qos
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_id
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_user
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_ready
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/ar_valid
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_valid
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_data
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_strb
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_user
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_last
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/w_ready
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_data
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_resp
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_last
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_id
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_user
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_ready
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/r_valid
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/b_resp
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/b_id
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/b_user
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/b_ready
add wave -noupdate -group {SOC BUS SOC L2 MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_l2_master/b_valid
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_addr
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_prot
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_region
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_len
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_size
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_burst
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_lock
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_cache
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_qos
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_id
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_user
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_ready
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/aw_valid
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_addr
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_prot
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_region
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_len
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_size
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_burst
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_lock
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_cache
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_qos
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_id
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_user
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_ready
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/ar_valid
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_valid
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_data
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_strb
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_user
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_last
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/w_ready
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_data
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_resp
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_last
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_id
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_user
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_ready
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/r_valid
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/b_resp
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/b_id
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/b_user
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/b_ready
add wave -noupdate -group {SOC BUS SOC EXT MASTER} /tb/ulpsoc_wrap_i/ulpsoc_i/soc_bus_wrap_i/soc_ext_master/b_valid
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4563871234 ps} 0}
configure wave -namecolwidth 660
configure wave -valuecolwidth 292
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4563859946 ps} {4563879027 ps}
