onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {SOC PERIPHERALS}
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_addr
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_prot
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_region
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_len
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_size
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_burst
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_lock
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_cache
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_qos
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_id
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_user
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_ready
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/aw_valid
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_addr
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_prot
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_region
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_len
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_size
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_burst
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_lock
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_cache
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_qos
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_id
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_user
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_ready
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/ar_valid
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_valid
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_data
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_strb
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_user
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_last
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/w_ready
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_data
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_resp
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_last
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_id
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_user
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_ready
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/r_valid
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/b_resp
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/b_id
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/b_user
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/b_ready
add wave -noupdate -group ROM_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_slave/b_valid
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_addr
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_prot
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_region
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_len
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_size
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_burst
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_lock
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_cache
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_qos
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_id
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_user
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_ready
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/aw_valid
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_addr
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_prot
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_region
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_len
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_size
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_burst
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_lock
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_cache
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_qos
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_id
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_user
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_ready
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/ar_valid
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_valid
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_data
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_strb
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_user
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_last
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/w_ready
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_data
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_resp
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_last
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_id
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_user
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_ready
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/r_valid
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/b_resp
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/b_id
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/b_user
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/b_ready
add wave -noupdate -group SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_slave/b_valid
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_addr
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_prot
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_region
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_len
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_size
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_burst
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_lock
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_cache
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_qos
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_id
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_user
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_ready
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/aw_valid
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_addr
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_prot
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_region
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_len
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_size
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_burst
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_lock
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_cache
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_qos
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_id
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_user
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_ready
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/ar_valid
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_valid
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_data
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_strb
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_user
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_last
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/w_ready
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_data
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_resp
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_last
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_id
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_user
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_ready
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/r_valid
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/b_resp
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/b_id
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/b_user
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/b_ready
add wave -noupdate -group CVP_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/cvp_slave/b_valid
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_addr
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_prot
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_region
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_len
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_size
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_burst
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_lock
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_cache
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_qos
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_id
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_user
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_ready
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/aw_valid
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_addr
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_prot
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_region
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_len
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_size
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_burst
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_lock
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_cache
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_qos
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_id
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_user
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_ready
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/ar_valid
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_valid
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_data
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_strb
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_user
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_last
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/w_ready
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_data
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_resp
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_last
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_id
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_user
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_ready
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/r_valid
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/b_resp
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/b_id
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/b_user
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/b_ready
add wave -noupdate -group CLK_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/clk_slave/b_valid
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_addr
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_prot
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_region
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_len
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_size
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_burst
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_lock
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_cache
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_qos
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_id
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_user
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_ready
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/aw_valid
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_addr
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_prot
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_region
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_len
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_size
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_burst
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_lock
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_cache
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_qos
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_id
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_user
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_ready
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/ar_valid
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_valid
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_data
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_strb
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_user
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_last
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/w_ready
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_data
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_resp
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_last
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_id
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_user
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_ready
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/r_valid
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/b_resp
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/b_id
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/b_user
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/b_ready
add wave -noupdate -group SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/spi_master/b_valid
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_addr
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_prot
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_region
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_len
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_size
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_burst
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_lock
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_cache
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_qos
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_id
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_user
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_ready
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/aw_valid
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_addr
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_prot
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_region
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_len
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_size
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_burst
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_lock
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_cache
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_qos
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_id
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_user
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_ready
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/ar_valid
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_valid
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_data
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_strb
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_user
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_last
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/w_ready
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_data
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_resp
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_last
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_id
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_user
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_ready
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/r_valid
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/b_resp
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/b_id
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/b_user
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/b_ready
add wave -noupdate -group JTAG_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/jtag_master/b_valid
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_mem_if_i/clk_i
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/rom_mem_if_i/rst_ni
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/boot_rom_i/clk_i
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/boot_rom_i/rst_ni
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/boot_rom_i/init_ni
add wave -noupdate -group BOOT_ROM /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/boot_rom_i/test_mode_i
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/clk_i
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/rst_ni
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/events_o
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_clk
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_csn0
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_csn1
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_csn2
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_csn3
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_mode
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdo0
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdo1
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdo2
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdo3
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdi0
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdi1
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdi2
add wave -noupdate -group AXI_SPI_MASTER /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_master_i/spi_sdi3
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/clk_i
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/rst_ni
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/test_mode
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_clk
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_cs
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_mode
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdo0
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdo1
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdo2
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdo3
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdi0
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdi1
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdi2
add wave -noupdate -group AXI_SPI_SLAVE /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_spi_slave_i/spi_sdi3
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/clk_i
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/rst_ni
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_req
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_wr_rd
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_add
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_be
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_data
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_ack
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_error
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp1_pwr_r_data
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_req
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_wr_rd
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_add
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_be
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_data
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_ack
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_error
add wave -noupdate -group AXI_CVP -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_cvp_if_i/cvp2_pwr_r_data
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/clk_i
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/rst_ni
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/gpio_in
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/gpio_out
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/gpio_dir
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/gpio_mux
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/uart_tx
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/uart_rx
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/clk_div0
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/clk_div0_valid
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/clk_div1
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/clk_div1_valid
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/wm_tcdm
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/rm_tcdm
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/int_gpio_in
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/int_gpio_out
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/int_gpio_dir
add wave -noupdate -group AXI_GPREG /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_gpreg_i/int_gpio_mux
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/tck_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/trst_ni
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/tms_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/td_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/td_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clk_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/rst_ni
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/fll_bypass_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/test_mode_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/scan_compress_mode_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/wm_tcdm
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/rm_tcdm
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/wm_l2_mem
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/rm_l2_mem
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/testmodereg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bistreg_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bistreg_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/shift
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/update
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/capture
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_sel
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_sel
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_sel
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_sel
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/scan_i
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axiscan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxscan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatescan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confscan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bistscan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/testmodescan_o
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_capture_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_shift_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_update_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_capture_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_shift_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_update_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_capture_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_shift_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_update_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_capture_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_shift_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_update_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/update_enable_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/enable
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/trst_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/test_mode
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/scan_compress_mode
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/fll_bypass
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/shift_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/update_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/capture_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/axireg_sel_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bbmuxreg_sel_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/clkgatereg_sel_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/confreg_sel_syn
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bist_en
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/testmodereg_sel
add wave -noupdate -group AXI_JTAG_WRAP /tb/ulpsoc_wrap_i/ulpsoc_i/soc_peripherals_i/axi_jtag_wrap_i/bistreg_sel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {78525458 ps} 0} {{Cursor 2} {78547730 ps} 0}
configure wave -namecolwidth 606
configure wave -valuecolwidth 292
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {78457064 ps} {78616124 ps}
