set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp9/xilinx_l2_mem_8192x64_dp2_in_context.xdc rfile:../dcp9/xilinx_l2_mem_8192x64_dp2_in_context.xdc id:1 order:EARLY scoped_inst:l2_ram_i/l2_mem_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:2 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[0].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:3 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[1].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:4 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[2].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:5 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[3].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:6 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[4].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:7 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[5].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:8 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[6].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:9 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[7].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:10 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[8].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:11 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[9].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:12 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[10].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:13 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[11].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:14 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[12].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:15 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[13].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:16 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[14].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:17 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[15].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:18 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[16].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:19 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[17].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:20 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[18].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:21 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[19].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:22 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[20].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:23 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[21].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:24 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[22].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:25 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[23].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:26 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[24].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:27 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[25].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:28 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[26].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:29 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[27].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:30 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[28].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:31 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[29].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:32 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[30].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc rfile:../dcp11/xilinx_tcdm_bank_4096x64_asym_in_context.xdc id:33 order:EARLY scoped_inst:{tcdm_sram_island/bram_bank_gen[31].bank_4096_asym_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:34 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[0].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:35 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[1].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:36 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[2].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:37 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[3].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:38 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[4].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:39 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[5].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:40 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[6].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:41 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[7].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:42 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[8].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:43 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[9].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:44 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[10].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:45 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[11].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:46 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[12].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:47 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[13].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:48 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[14].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/.Xil/Vivado-12550-mcarr/dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc rfile:../dcp13/xilinx_tcdm_bank_2048x64_in_context.xdc id:49 order:EARLY scoped_inst:{hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[15].bank_2048_gen.tcdm_bank_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nur/NEURAghe/neuraghe_1.9/fpga/soc/soc.runs/synth_2/dont_touch.xdc rfile:../../../dont_touch.xdc id:50} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins l2_ram_i/l2_mem_i/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins l2_ram_i/l2_mem_i/clkb]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells l2_ram_i/l2_mem_i]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[0].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[0].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[0].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[1].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[1].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[1].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[2].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[2].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[2].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[3].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[3].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[3].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[4].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[4].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[4].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[5].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[5].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[5].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[6].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[6].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[6].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[7].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[7].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[7].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[8].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[8].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[8].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[9].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[9].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[9].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[10].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[10].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[10].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[11].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[11].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[11].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[12].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[12].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[12].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[13].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[13].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[13].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[14].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[14].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[14].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[15].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[15].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[15].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[16].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[16].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[16].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[17].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[17].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[17].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[18].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[18].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[18].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[19].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[19].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[19].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[20].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[20].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[20].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[21].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[21].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[21].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:24 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[22].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[22].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:24 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[22].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:25 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[23].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[23].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:25 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[23].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:26 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[24].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[24].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[24].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:27 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[25].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[25].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[25].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:28 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[26].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:28 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[26].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:28 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[26].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:29 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[27].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:29 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[27].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:29 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[27].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:30 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[28].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:30 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[28].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:30 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[28].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:31 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[29].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:31 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[29].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:31 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[29].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:32 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[30].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:32 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[30].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:32 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[30].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:33 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[31].bank_4096_asym_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:33 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {tcdm_sram_island/bram_bank_gen[31].bank_4096_asym_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:33 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {tcdm_sram_island/bram_bank_gen[31].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:34 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[0].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:34 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[0].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:34 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[0].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:35 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[1].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:35 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[1].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:35 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[1].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:36 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[2].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:36 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[2].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:36 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[2].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:37 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[3].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:37 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[3].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:37 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[3].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:38 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[4].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:38 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[4].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:38 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[4].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:39 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[5].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:39 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[5].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:39 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[5].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:40 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[6].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:40 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[6].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:40 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[6].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:41 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[7].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:41 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[7].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:41 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[7].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:42 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[8].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:42 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[8].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:42 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[8].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:43 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[9].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:43 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[9].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:43 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[9].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:44 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[10].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:44 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[10].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:44 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[10].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:45 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[11].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:45 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[11].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:45 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[11].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:46 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[12].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:46 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[12].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:46 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[12].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:47 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[13].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:47 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[13].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:47 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[13].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:48 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[14].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:48 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[14].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:48 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[14].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:SCOPED_XDC file:49 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[15].bank_2048_gen.tcdm_bank_i/clka}]
set_property src_info {type:SCOPED_XDC file:49 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[15].bank_2048_gen.tcdm_bank_i/clkb}]
set_property src_info {type:SCOPED_XDC file:49 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[15].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells core_data_memory_i/mem_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[0].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[10].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[11].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[12].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[13].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[14].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[15].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[1].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[2].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[3].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[4].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[5].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[6].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[7].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[8].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {hwce_wrap_i/hwce_top_i/weights_mem_dp_wrap_i/banks_gen[9].bank_2048_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells l2_ram_i/l2_mem_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[0].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[10].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[11].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[12].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[13].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[14].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[15].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[16].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[17].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[18].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[19].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[1].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[20].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[21].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[22].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[23].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[24].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[25].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[26].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[27].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[28].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[29].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[2].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[30].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[31].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[3].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[4].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[5].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[6].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[7].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[8].bank_4096_asym_gen.tcdm_bank_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {tcdm_sram_island/bram_bank_gen[9].bank_4096_asym_gen.tcdm_bank_i}]
