onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {CORE 0 REGION}
add wave -noupdate -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/cluster_int_region_i/cluster_interconnect_wrap_i/clk_i
add wave -noupdate -radix hexadecimal /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/cluster_int_region_i/cluster_interconnect_wrap_i/rst_ni
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/clk_i}
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/rst_ni}
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/init_ni}
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/cluster_id_i}
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/fetch_en_i}
add wave -noupdate -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/test_mode_i}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/req}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/add}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/we}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/wdata}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/be}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/gnt}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/r_opc}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/r_rdata}
add wave -noupdate -group CORE_0_TCDM_DATA_MASTER -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/tcdm_data_master/r_valid}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/req}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/add}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/we}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/wdata}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/be}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/gnt}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/r_opc}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/r_rdata}
add wave -noupdate -group CORE_0_DMA_CTRL_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/dma_ctrl_master/r_valid}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/req}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/add}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/we}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/wdata}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/be}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/gnt}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/id}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/r_valid}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/r_opc}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/r_id}
add wave -noupdate -group CORE_0_PERIPH_DATA_MASTER {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_data_master/r_rdata}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/barrier}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/busy}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/exec_cancel}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/exec_stall}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/req}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/add}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/we}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/wdata}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/be}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/gnt}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/r_gnt}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/r_valid}
add wave -noupdate -group CORE_0_S_CORE_BUS -radix hexadecimal {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/s_core_bus/r_rdata}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/clk}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/rst_ni}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_req_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_add_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_type_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_wdata_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_be_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_gnt_o}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_gnt_i}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_valid_o}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_rdata_o}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_opc_o}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_req_o_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_add_o_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_type_o_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_wdata_o_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_be_o_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_gnt_i_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_valid_i_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_rdata_i_SH}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_req_o_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_add_o_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_type_o_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_wdata_o_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_be_o_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_gnt_i_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_valid_i_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_opc_i_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/data_r_rdata_i_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_req_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_gnt_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_data_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_valid_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_opc_PE}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_data_PE_0}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_valid_PE_0}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/s_data_r_opc_PE_0}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/CS}
add wave -noupdate -group CORE_0_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/core_demux_i/NS}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/clk}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/rst_ni}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_req_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_add_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_type_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_wdata_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_be_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_gnt_o}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_gnt_i}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_valid_o}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_rdata_o}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_opc_o}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_req_o_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_add_o_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_type_o_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_wdata_o_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_be_o_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_gnt_i_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_valid_i_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_rdata_i_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/data_r_opc_i_MH}
add wave -noupdate -group CORE_0_PERIPH_DEMUX {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/periph_demux_i/request_destination}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/clk}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/rst_n}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/boot_addr_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/instr_rdata_id_o}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/current_pc_if_o}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/current_pc_id_o}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/instr_rdata_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/instr_addr_o}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/force_nop_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/exception_pc_reg_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_from_regfile_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_from_immediate_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_from_hwloop_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_mux_sel_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_mux_boot_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/exc_pc_mux_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/pc_from_dbg_npc}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/stall_if_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/stall_id_i}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/next_pc}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/exc_pc}
add wave -noupdate -group OR10N_0_IF_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/if_stage_i/instr_rdata_int}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/clk}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/rst_n}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/fetch_enable_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/core_busy_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/instr_rdata_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/instr_req_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/instr_gnt_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/instr_ack_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_from_immediate_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_mux_sel_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_mux_boot_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/exc_pc_mux_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/force_nop_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_from_regfile_fw_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/current_pc_if_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/current_pc_id_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/stall_if_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/stall_id_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/stall_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/stall_wb_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/sr_flag_fw_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_rb_data_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_a_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_b_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_c_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operator_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/vector_mode_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_cmp_mode_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_vec_ext_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/eoc_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_is_running_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_sel_subword_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_signed_mode_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_use_carry_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_mac_en_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_waddr_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_wdata_mux_sel_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_we_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_waddr_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_we_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/prepost_useincr_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_we_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_regid_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_wb_mux_sel_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_cnt_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_dec_cnt_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_targ_addr_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/sp_we_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_we_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_type_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_sign_ext_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_req_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_ack_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_rvalid_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_flag_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_carry_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_overflow_ex_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_dsx_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/irq_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/irq_nm_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/irq_enable_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/save_pc_if_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/save_pc_id_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/save_sr_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/restore_sr_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_start_addr_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_end_addr_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_counter_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_flush_pipe_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pipe_flushed_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_st_en_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_dsr_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_stall_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_trap_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_reg_mux_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_reg_we_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_reg_addr_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_reg_wdata_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_reg_rdata_o}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/dbg_set_npc_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_wdata_ex_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_waddr_wb_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_we_wb_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_wdata_wb_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_waddr_fw_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_we_fw_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_wdata_fw_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/wdata_reg_i}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate26_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate5n11_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate16_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate21z_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate21s_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate_b}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate13z_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate8z_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate16z_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate11s_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate_vec_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/current_pc}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/exc_pc_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_mux_sel_int}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/irq_present}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/jump_in_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/jump_in_ex}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/illegal_insn}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/trap_insn}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pipe_flush}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/pc_valid}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/clear_isr_running}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_addr_ra_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_addr_rb_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_addr_rc_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_waddr_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_waddr_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_we_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_data_ra_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_data_rb_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_data_rc_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/imm_sign_ext_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operator}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_op_a_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_op_b_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/scalar_replication}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/vector_mode}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_cmp_mode}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_vec_ext}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_pc_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/immediate_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_is_running}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_sel_subword}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_signed_mode}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_use_carry}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/mult_mac_en}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/eoc}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_waddr_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_wdata_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_we_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/regfile_prepost_waddr_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/sp_we_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_we_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_type_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_sign_ext_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/data_req_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_regid}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_we}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_wb_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_cnt_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_cnt}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_jump}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/hwloop_enable}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_flag}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_carry}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/set_overflow}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/prepost_useincr}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_a_fw_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_b_fw_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_c_fw_mux_sel}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_a_fw_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_b_fw_id}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_b_fw_int}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_a}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_b}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/alu_operand_c}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_b}
add wave -noupdate -group OR10N_0_ID_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/id_stage_i/operand_b_int}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/clk}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/rst_n}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_operator_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_operand_a_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_operand_b_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_operand_c_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_carry_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_flag_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/vector_mode_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_cmp_mode_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_vec_ext_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_is_running_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_sel_subword_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_signed_mode_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_use_carry_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_mac_en_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/data_addr_ex_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/stall_ex_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/stall_wb_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_prepost_waddr_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_prepost_we_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/prepost_useincr_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_waddr_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_wdata_mux_sel_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_wb_mux_sel_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_pc_plus4_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_cnt_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/set_overflow_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/set_carry_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_we_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/eoc_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_rb_data_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/sp_we_i}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_flag_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/carry_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/overflow_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/set_overflow_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/set_carry_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_wdata_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_waddr_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_wdata_mux_sel_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_we_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_rb_data_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_start_data_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_end_data_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/hwloop_cnt_data_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/sp_we_wb_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/eoc_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_prepost_waddr_fw_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_prepost_we_fw_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_prepost_wdata_fw_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/regfile_wdata_fw_o}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_overflow_int}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_carry_int}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_result}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/alu_adder_lsu_int}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_result}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_carry_int}
add wave -noupdate -group OR10N_0_EX_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/ex_stage_i/mult_overflow_int}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/regfile_wdata_mux_sel_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/ex_result_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/sp_rdata_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/data_rdata_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/lsu_data_reg_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/regfile_wdata_o}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/wdata_reg_o}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/eoc_i}
add wave -noupdate -group OR10N_0_WB_STAGE {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/wb_stage_i/eoc_o}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/clk}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/rst_n}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/req_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/addr_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/ack_o}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/rdata_o}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/instr_req_o}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/instr_addr_o}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/instr_gnt_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/instr_r_valid_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/instr_r_rdata_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/stall_if_i}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/CS}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/NS}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/save_rdata}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/rdata_Q}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/wait_gnt}
add wave -noupdate -group OR10N_0_FETCH_IF {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/instr_core_interface_i/addr_Q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/clk}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/rst_n}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_we_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_type_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_wdata_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_sign_ext_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_rdata_ex_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/lsu_data_reg_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_req_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_addr_ex_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_ack_int_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_req_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_addr_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_we_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_be_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_wdata_o}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_rdata_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_rvalid_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_gnt_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/ex_stall_i}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_type_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/rdata_offset_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_sign_ext_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_be}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_be_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_wdata}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_wdata_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_we_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_addr_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/request_entered}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/CS}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/NS}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/save_rdata}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/rdata_q}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/data_rdata_int}
add wave -noupdate -group OR1ON_0_LSU {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/CORE[0]/core_region_i/ORION_CORE/load_store_unit_i/latch_rdata}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {45191995468 ps} 0} {{Cursor 2} {0 ps} 0}
configure wave -namecolwidth 564
configure wave -valuecolwidth 120
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {203708956672 ps}
