onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider TCDM
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_4 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_5 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_6 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/clk_i}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/rst_ni}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/re_ni}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/we_ni}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/be_ni}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/add_i}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/wdata_i}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/rdata_o}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/rdata_DEST}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/re_n_int}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/we_n_int}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/rdata_int}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/CLK}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/INITN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/CEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/A}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/WEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/D}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/BEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/Q}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/M}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/CLK}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/INITN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/CEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/A}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/WEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/D}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/BEN}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/Q}
add wave -noupdate -group TCDM_SCM_BANK_7 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/M}
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/clk_i
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/rst_ni
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/init_ni
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/rm_i
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/wm_i
add wave -noupdate -group TCDM_SRAM_REGION_0 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/test_mode_i
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_0 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/clk_i
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/rst_ni
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/init_ni
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/rm_i
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/wm_i
add wave -noupdate -group TCDM_SRAM_REGION_1 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/test_mode_i
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_1 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/clk_i
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/rst_ni
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/init_ni
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/rm_i
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/wm_i
add wave -noupdate -group TCDM_SRAM_REGION_2 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/test_mode_i
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_2 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/clk_i
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/rst_ni
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/init_ni
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/rm_i
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/wm_i
add wave -noupdate -group TCDM_SRAM_REGION_3 /tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/test_mode_i
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/CLK}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/RSTN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/INITN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/CSN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/WEN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/WMN}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/RM}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/WM}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/A}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/D}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/Q}
add wave -noupdate -group TCDM_SRAM_REGION_3 {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/TM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[0]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[1]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[2]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[3]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[4]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[5]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[6]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_0/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_scm_island/BANK[7]/scm_bank_i/scm_i_1/MEM}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[0]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_0/BANK[1]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[0]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_1/BANK[1]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[0]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_2/BANK[1]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[0]/tcdm_bank_i/cut/Array}
add wave -noupdate -group TCDM_CONTENT {/tb/ulpsoc_wrap_i/ulpsoc_i/cluster_i/tcdm_sram_island_3/BANK[1]/tcdm_bank_i/cut/Array}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2175610000 ps} 0}
configure wave -namecolwidth 606
configure wave -valuecolwidth 292
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {8846103063 ps} {8927541103 ps}
