#ifndef __ARCHI_PR_CONTROL_H__
#define __ARCHI_PR_CONTROL_H__

#define BANK_PR_CTRL_FETCH_ENABLE_ROFF 0x0
#define BANK_PR_CTRL_SOFT_RESET_ROFF 0x10
#define BANK_PR_CTRL_BOOT_ADDRESS_ROFF 0x14

#endif
