# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.cache/wt [current_project]
set_property parent.project_path /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/nur/pulp/ip_repo/ulp_soc_controller
  /home/nur/pulp/twindma_repo
  /home/nur/pulp/ip_repo/ulpsoc_wrap_3
  /home/nur/pulp/ip_repo/ulpsoc_wrap_2
  /home/nur/pulp/ip_repo/ulpsoc_wrap_1
} [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.vhd
add_files /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_0/base_zynq_design_axi_protocol_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_1_0/base_zynq_design_axi_protocol_converter_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_1/base_zynq_design_axi_protocol_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_3_0/base_zynq_design_axi_protocol_converter_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_2_0/base_zynq_design_axi_protocol_converter_2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/base_zynq_design_ooc.xdc]
set_property is_locked true [get_files /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd]

read_edif /home/nur/neuraghe_2.0/neuraghe_2.0/fpga/soc/ulpsoc.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/constrs_1/new/ioconstraint.xdc
set_property used_in_implementation false [get_files /home/nur/neuraghe_2.0/neuraghe_2.0/pulp_on_zynq/pulp_on_zynq.srcs/constrs_1/new/ioconstraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top base_zynq_design_wrapper -part xc7z045ffg900-2 -directive AreaOptimized_high -control_set_opt_threshold 1


write_checkpoint -force -noxdef base_zynq_design_wrapper.dcp

catch { report_utilization -file base_zynq_design_wrapper_utilization_synth.rpt -pb base_zynq_design_wrapper_utilization_synth.pb }
