# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ioconstraint.xdc

# Block Designs: bd/base_zynq_design/base_zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design || ORIG_REF_NAME==base_zynq_design}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_soc_AXI_ctrl_v1_0_0_0/base_zynq_design_soc_AXI_ctrl_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_soc_AXI_ctrl_v1_0_0_0 || ORIG_REF_NAME==base_zynq_design_soc_AXI_ctrl_v1_0_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_0/base_zynq_design_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_protocol_converter_0_0 || ORIG_REF_NAME==base_zynq_design_axi_protocol_converter_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_1_0/base_zynq_design_axi_protocol_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_protocol_converter_1_0 || ORIG_REF_NAME==base_zynq_design_axi_protocol_converter_1_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_dwidth_converter_0_0 || ORIG_REF_NAME==base_zynq_design_axi_dwidth_converter_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_clk_wiz_1_0 || ORIG_REF_NAME==base_zynq_design_clk_wiz_1_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_1/base_zynq_design_axi_protocol_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_protocol_converter_0_1 || ORIG_REF_NAME==base_zynq_design_axi_protocol_converter_0_1}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_3_0/base_zynq_design_axi_protocol_converter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_protocol_converter_3_0 || ORIG_REF_NAME==base_zynq_design_axi_protocol_converter_3_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_xbar_0 || ORIG_REF_NAME==base_zynq_design_xbar_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_nuraghe_soc_1_0/base_zynq_design_nuraghe_soc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_nuraghe_soc_1_0 || ORIG_REF_NAME==base_zynq_design_nuraghe_soc_1_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_2_0/base_zynq_design_axi_protocol_converter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_protocol_converter_2_0 || ORIG_REF_NAME==base_zynq_design_axi_protocol_converter_2_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_ds_0 || ORIG_REF_NAME==base_zynq_design_auto_ds_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_0 || ORIG_REF_NAME==base_zynq_design_auto_pc_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_us_0 || ORIG_REF_NAME==base_zynq_design_auto_us_0}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_0/base_zynq_design_axi_protocol_converter_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_1_0/base_zynq_design_axi_protocol_converter_1_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_dwidth_converter_0_0 || ORIG_REF_NAME==base_zynq_design_axi_dwidth_converter_0_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_dwidth_converter_0_0/base_zynq_design_axi_dwidth_converter_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_clk_wiz_1_0 || ORIG_REF_NAME==base_zynq_design_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_clk_wiz_1_0 || ORIG_REF_NAME==base_zynq_design_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_clk_wiz_1_0/base_zynq_design_clk_wiz_1_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_0_1/base_zynq_design_axi_protocol_converter_0_1_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_3_0/base_zynq_design_axi_protocol_converter_3_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_protocol_converter_2_0/base_zynq_design_axi_protocol_converter_2_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_ds_0 || ORIG_REF_NAME==base_zynq_design_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_ds_0/base_zynq_design_auto_ds_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_us_0 || ORIG_REF_NAME==base_zynq_design_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_us_0/base_zynq_design_auto_us_0_ooc.xdc

# XDC: bd/base_zynq_design/base_zynq_design_ooc.xdc
