# Definitional proc to organize widgets for parameters.
proc init_gui { IPINST } {
  ipgui::add_param $IPINST -name "Component_Name"
  #Adding Page
  set Page_0 [ipgui::add_page $IPINST -name "Page 0" -display_name {Description}]
  set_property tooltip {Description} ${Page_0}
  ipgui::add_static_text $IPINST -name "Description" -parent ${Page_0} -text {IP wrapper for EDIF file generated by syntesis scripts in fpga folder of nuraghe.
Remember to add the .edf file to source file list of the project and to make ir a global include.}


}


