# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z045ffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.cache/wt [current_project]
set_property parent.project_path /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:0.9 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.xci
set_property is_locked true [get_files /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top xilinx_l2_mem_8192x64_dp -part xc7z045ffg900-2 -mode out_of_context
rename_ref -prefix_all xilinx_l2_mem_8192x64_dp_
write_checkpoint -noxdef xilinx_l2_mem_8192x64_dp.dcp
catch { report_utilization -file xilinx_l2_mem_8192x64_dp_utilization_synth.rpt -pb xilinx_l2_mem_8192x64_dp_utilization_synth.pb }
if { [catch {
  file copy -force /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.runs/xilinx_l2_mem_8192x64_dp_synth_1/xilinx_l2_mem_8192x64_dp.dcp /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.ip_user_files/ip/xilinx_l2_mem_8192x64_dp]} {
  catch { 
    file copy -force /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_stub.v /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.ip_user_files/ip/xilinx_l2_mem_8192x64_dp
  }
}

if {[file isdir /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.ip_user_files/ip/xilinx_l2_mem_8192x64_dp]} {
  catch { 
    file copy -force /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.srcs/sources_1/ip/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp_stub.vhdl /home/gian/pulp/nuraghe/fpga/ips/xilinx_l2_mem_8192x64_dp/xilinx_l2_mem_8192x64_dp.ip_user_files/ip/xilinx_l2_mem_8192x64_dp
  }
}
