# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_or1kfsim', [dirname(__file__)])
        except ImportError:
            import _or1kfsim
            return _or1kfsim
        if fp is not None:
            try:
                _mod = imp.load_module('_or1kfsim', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _or1kfsim = swig_import_helper()
    del swig_import_helper
else:
    import _or1kfsim
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class trace(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, trace, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, trace, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _or1kfsim.new_trace()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["isActive"] = _or1kfsim.trace_isActive_set
    __swig_getmethods__["isActive"] = _or1kfsim.trace_isActive_get
    if _newclass:
        isActive = _swig_property(_or1kfsim.trace_isActive_get, _or1kfsim.trace_isActive_set)
    __swig_setmethods__["path"] = _or1kfsim.trace_path_set
    __swig_getmethods__["path"] = _or1kfsim.trace_path_get
    if _newclass:
        path = _swig_property(_or1kfsim.trace_path_get, _or1kfsim.trace_path_set)

    def dumpMsg(self, fmt: 'char const *') -> "void":
        return _or1kfsim.trace_dumpMsg(self, fmt)

    def dumpUserMsg(self, fmt: 'char const *') -> "void":
        return _or1kfsim.trace_dumpUserMsg(self, fmt)

    def dumpWarning(self, fmt: 'char const *') -> "void":
        return _or1kfsim.trace_dumpWarning(self, fmt)

    def setComponent(self, comp: 'component') -> "void":
        return _or1kfsim.trace_setComponent(self, comp)
    __swig_destroy__ = _or1kfsim.delete_trace
    __del__ = lambda self: None
trace_swigregister = _or1kfsim.trace_swigregister
trace_swigregister(trace)

class slavePort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, slavePort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, slavePort, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _or1kfsim.new_slavePort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_slavePort
    __del__ = lambda self: None

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.slavePort_getSlavePortResync(self, initiatorEngine, targetEngine)

    def setName(self, name: 'string') -> "void":
        return _or1kfsim.slavePort_setName(self, name)

    def setComp(self, comp: 'component') -> "void":
        return _or1kfsim.slavePort_setComp(self, comp)

    def getPortClass(self) -> "unsigned long long":
        return _or1kfsim.slavePort_getPortClass(self)
    __swig_setmethods__["comp"] = _or1kfsim.slavePort_comp_set
    __swig_getmethods__["comp"] = _or1kfsim.slavePort_comp_get
    if _newclass:
        comp = _swig_property(_or1kfsim.slavePort_comp_get, _or1kfsim.slavePort_comp_set)
    __swig_setmethods__["name"] = _or1kfsim.slavePort_name_set
    __swig_getmethods__["name"] = _or1kfsim.slavePort_name_get
    if _newclass:
        name = _swig_property(_or1kfsim.slavePort_name_get, _or1kfsim.slavePort_name_set)

    def getName(self) -> "char *":
        return _or1kfsim.slavePort_getName(self)
    __swig_setmethods__["next"] = _or1kfsim.slavePort_next_set
    __swig_getmethods__["next"] = _or1kfsim.slavePort_next_get
    if _newclass:
        next = _swig_property(_or1kfsim.slavePort_next_get, _or1kfsim.slavePort_next_set)
    __swig_setmethods__["slaveId"] = _or1kfsim.slavePort_slaveId_set
    __swig_getmethods__["slaveId"] = _or1kfsim.slavePort_slaveId_get
    if _newclass:
        slaveId = _swig_property(_or1kfsim.slavePort_slaveId_get, _or1kfsim.slavePort_slaveId_set)
slavePort_swigregister = _or1kfsim.slavePort_swigregister
slavePort_swigregister(slavePort)

class inPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, inPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, inPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _or1kfsim.inPort_data_set
    __swig_getmethods__["data"] = _or1kfsim.inPort_data_get
    if _newclass:
        data = _swig_property(_or1kfsim.inPort_data_get, _or1kfsim.inPort_data_set)
    __swig_setmethods__["comp"] = _or1kfsim.inPort_comp_set
    __swig_getmethods__["comp"] = _or1kfsim.inPort_comp_get
    if _newclass:
        comp = _swig_property(_or1kfsim.inPort_comp_get, _or1kfsim.inPort_comp_set)
    __swig_setmethods__["targetComp"] = _or1kfsim.inPort_targetComp_set
    __swig_getmethods__["targetComp"] = _or1kfsim.inPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_or1kfsim.inPort_targetComp_get, _or1kfsim.inPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _or1kfsim.inPort_targetEval_set
    __swig_getmethods__["targetEval"] = _or1kfsim.inPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_or1kfsim.inPort_targetEval_get, _or1kfsim.inPort_targetEval_set)
    __swig_setmethods__["widthWords"] = _or1kfsim.inPort_widthWords_set
    __swig_getmethods__["widthWords"] = _or1kfsim.inPort_widthWords_get
    if _newclass:
        widthWords = _swig_property(_or1kfsim.inPort_widthWords_get, _or1kfsim.inPort_widthWords_set)

    def checkTarget(self) -> "void":
        return _or1kfsim.inPort_checkTarget(self)

    def read32(self) -> "uint32_t":
        return _or1kfsim.inPort_read32(self)

    def readAt(self, wordIndex: 'int') -> "uint32_t":
        return _or1kfsim.inPort_readAt(self, wordIndex)

    def copy(self, data: 'uint32_t *') -> "void":
        return _or1kfsim.inPort_copy(self, data)

    def __init__(self):
        this = _or1kfsim.new_inPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_inPort
    __del__ = lambda self: None
inPort_swigregister = _or1kfsim.inPort_swigregister
inPort_swigregister(inPort)

class outPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, outPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, outPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["port"] = _or1kfsim.outPort_port_set
    __swig_getmethods__["port"] = _or1kfsim.outPort_port_get
    if _newclass:
        port = _swig_property(_or1kfsim.outPort_port_get, _or1kfsim.outPort_port_set)
    __swig_setmethods__["data"] = _or1kfsim.outPort_data_set
    __swig_getmethods__["data"] = _or1kfsim.outPort_data_get
    if _newclass:
        data = _swig_property(_or1kfsim.outPort_data_get, _or1kfsim.outPort_data_set)
    __swig_setmethods__["ioId"] = _or1kfsim.outPort_ioId_set
    __swig_getmethods__["ioId"] = _or1kfsim.outPort_ioId_get
    if _newclass:
        ioId = _swig_property(_or1kfsim.outPort_ioId_get, _or1kfsim.outPort_ioId_set)
    __swig_setmethods__["comp"] = _or1kfsim.outPort_comp_set
    __swig_getmethods__["comp"] = _or1kfsim.outPort_comp_get
    if _newclass:
        comp = _swig_property(_or1kfsim.outPort_comp_get, _or1kfsim.outPort_comp_set)
    __swig_setmethods__["targetIoId"] = _or1kfsim.outPort_targetIoId_set
    __swig_getmethods__["targetIoId"] = _or1kfsim.outPort_targetIoId_get
    if _newclass:
        targetIoId = _swig_property(_or1kfsim.outPort_targetIoId_get, _or1kfsim.outPort_targetIoId_set)
    __swig_setmethods__["targetComp"] = _or1kfsim.outPort_targetComp_set
    __swig_getmethods__["targetComp"] = _or1kfsim.outPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_or1kfsim.outPort_targetComp_get, _or1kfsim.outPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _or1kfsim.outPort_targetEval_set
    __swig_getmethods__["targetEval"] = _or1kfsim.outPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_or1kfsim.outPort_targetEval_get, _or1kfsim.outPort_targetEval_set)
    __swig_setmethods__["updated"] = _or1kfsim.outPort_updated_set
    __swig_getmethods__["updated"] = _or1kfsim.outPort_updated_get
    if _newclass:
        updated = _swig_property(_or1kfsim.outPort_updated_get, _or1kfsim.outPort_updated_set)

    def checkTarget(self) -> "void":
        return _or1kfsim.outPort_checkTarget(self)

    def write32(self, value: 'uint32_t') -> "void":
        return _or1kfsim.outPort_write32(self, value)

    def __init__(self):
        this = _or1kfsim.new_outPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_outPort
    __del__ = lambda self: None
outPort_swigregister = _or1kfsim.outPort_swigregister
outPort_swigregister(outPort)

class combRegInit(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, combRegInit, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, combRegInit, name)
    __repr__ = _swig_repr

    def __init__(self, port: 'outPort', data: 'uint32_t *'):
        this = _or1kfsim.new_combRegInit(port, data)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["port"] = _or1kfsim.combRegInit_port_set
    __swig_getmethods__["port"] = _or1kfsim.combRegInit_port_get
    if _newclass:
        port = _swig_property(_or1kfsim.combRegInit_port_get, _or1kfsim.combRegInit_port_set)
    __swig_setmethods__["data"] = _or1kfsim.combRegInit_data_set
    __swig_getmethods__["data"] = _or1kfsim.combRegInit_data_get
    if _newclass:
        data = _swig_property(_or1kfsim.combRegInit_data_get, _or1kfsim.combRegInit_data_set)
    __swig_destroy__ = _or1kfsim.delete_combRegInit
    __del__ = lambda self: None
combRegInit_swigregister = _or1kfsim.combRegInit_swigregister
combRegInit_swigregister(combRegInit)

class component(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, component, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, component, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _or1kfsim.new_component()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def setEngine(self, engineInstance: 'unsigned long') -> "void":
        return _or1kfsim.component_setEngine(self, engineInstance)

    def build(self) -> "int":
        return _or1kfsim.component_build(self)

    def start(self) -> "int":
        return _or1kfsim.component_start(self)

    def reset(self) -> "void":
        return _or1kfsim.component_reset(self)

    def close(self) -> "void":
        return _or1kfsim.component_close(self)
    __swig_destroy__ = _or1kfsim.delete_component
    __del__ = lambda self: None

    def state(self, name: 'char *') -> "void":
        return _or1kfsim.component_state(self, name)

    def memDump(self, base: 'unsigned int', size: 'unsigned int') -> "bool":
        return _or1kfsim.component_memDump(self, base, size)

    def getCycles(self) -> "int64_t":
        return _or1kfsim.component_getCycles(self)

    def disAllBkp(self) -> "void":
        return _or1kfsim.component_disAllBkp(self)

    def setBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int') -> "void":
        return _or1kfsim.component_setBkp(self, base, size, access)

    def checkBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int', matchAddr: 'unsigned int &', matchAccess: 'unsigned int &') -> "bool":
        return _or1kfsim.component_checkBkp(self, base, size, access, matchAddr, matchAccess)

    def reg(self, outPort: 'outPort', data: 'uint32_t *', localData: 'uint32_t **', inPort: 'inPort') -> "void":
        return _or1kfsim.component_reg(self, outPort, data, localData, inPort)

    def regOut(self, name: 'string', port: 'outPort') -> "void":
        return _or1kfsim.component_regOut(self, name, port)

    def regIn(self, *args) -> "void":
        return _or1kfsim.component_regIn(self, *args)

    def evalNetwork(self) -> "void":
        return _or1kfsim.component_evalNetwork(self)

    def commitNetwork(self) -> "void":
        return _or1kfsim.component_commitNetwork(self)

    def setNetwork(self, network: 'component') -> "void":
        return _or1kfsim.component_setNetwork(self, network)

    def eval(self) -> "void":
        return _or1kfsim.component_eval(self)

    def precommit(self) -> "void":
        return _or1kfsim.component_precommit(self)

    def commit(self) -> "void":
        return _or1kfsim.component_commit(self)

    def syncNextCycle(self, *args) -> "void":
        return _or1kfsim.component_syncNextCycle(self, *args)

    def syncOut(self, *args) -> "void":
        return _or1kfsim.component_syncOut(self, *args)

    def addCell(self, comp: 'component') -> "void":
        return _or1kfsim.component_addCell(self, comp)

    def connectNetworkOutputs(self) -> "void":
        return _or1kfsim.component_connectNetworkOutputs(self)

    def regSlave(self, name: 'string', port: 'slavePort') -> "void":
        return _or1kfsim.component_regSlave(self, name, port)

    def registerPowerTrace(self, trace: 'gv::powerTrace **', name: 'char *') -> "bool":
        return _or1kfsim.component_registerPowerTrace(self, trace, name)

    def confPowerTrace(self, trace: 'gv::powerTrace *') -> "void":
        return _or1kfsim.component_confPowerTrace(self, trace)

    def confVcdTrace(self, trace: 'gv::vcdTrace *', path: 'char const *', isActive: 'bool', file: 'long') -> "void":
        return _or1kfsim.component_confVcdTrace(self, trace, path, isActive, file)

    def getSlavePort(self, name: 'char *') -> "gv::slavePort *":
        return _or1kfsim.component_getSlavePort(self, name)

    def getSlavePortResync(self, initiatorEngine: 'unsigned long long', port: 'slavePort') -> "gv::slavePort *":
        return _or1kfsim.component_getSlavePortResync(self, initiatorEngine, port)

    def regMaster(self, name: 'string', port: 'gv::masterPort *') -> "void":
        return _or1kfsim.component_regMaster(self, name, port)

    def getMasterName(self, index: 'unsigned int') -> "char const *":
        return _or1kfsim.component_getMasterName(self, index)

    def getSlaveName(self, index: 'unsigned int') -> "char const *":
        return _or1kfsim.component_getSlaveName(self, index)

    def getTrace(self, name: 'char const *') -> "gv::trace *":
        return _or1kfsim.component_getTrace(self, name)

    def getVcdTrace(self, name: 'char const *') -> "gv::vcdTrace *":
        return _or1kfsim.component_getVcdTrace(self, name)

    def getTraceName(self, index: 'unsigned int') -> "char const *":
        return _or1kfsim.component_getTraceName(self, index)

    def getVcdTraceName(self, index: 'unsigned int') -> "char const *":
        return _or1kfsim.component_getVcdTraceName(self, index)

    def linkMasterTo(self, name: 'char const *', slavePort: 'slavePort') -> "void":
        return _or1kfsim.component_linkMasterTo(self, name, slavePort)

    def regTrace(self, name: 'string', tr: 'trace') -> "void":
        return _or1kfsim.component_regTrace(self, name, tr)

    def regVcd(self, name: 'string', vcd: 'gv::vcdTrace *', width: 'int') -> "void":
        return _or1kfsim.component_regVcd(self, name, vcd, width)

    def regVcdString(self, name: 'string', vcd: 'gv::vcdTrace *') -> "void":
        return _or1kfsim.component_regVcdString(self, name, vcd)

    def getUserTrace(self) -> "gv::trace *":
        return _or1kfsim.component_getUserTrace(self)

    def getEngine(self) -> "engine *":
        return _or1kfsim.component_getEngine(self)

    def getPowerEngine(self) -> "gv::powerEngine *":
        return _or1kfsim.component_getPowerEngine(self)

    def confTrace(self, name: 'char const *', path: 'char const *', active: 'bool') -> "void":
        return _or1kfsim.component_confTrace(self, name, path, active)

    def reorderCell(self, nextComp: 'component') -> "void":
        return _or1kfsim.component_reorderCell(self, nextComp)

    def dequeueCell(self) -> "void":
        return _or1kfsim.component_dequeueCell(self)
    __swig_setmethods__["network"] = _or1kfsim.component_network_set
    __swig_getmethods__["network"] = _or1kfsim.component_network_get
    if _newclass:
        network = _swig_property(_or1kfsim.component_network_get, _or1kfsim.component_network_set)
    __swig_setmethods__["evaluated"] = _or1kfsim.component_evaluated_set
    __swig_getmethods__["evaluated"] = _or1kfsim.component_evaluated_get
    if _newclass:
        evaluated = _swig_property(_or1kfsim.component_evaluated_get, _or1kfsim.component_evaluated_set)
    __swig_setmethods__["path"] = _or1kfsim.component_path_set
    __swig_getmethods__["path"] = _or1kfsim.component_path_get
    if _newclass:
        path = _swig_property(_or1kfsim.component_path_get, _or1kfsim.component_path_set)
    __swig_setmethods__["evalCell"] = _or1kfsim.component_evalCell_set
    __swig_getmethods__["evalCell"] = _or1kfsim.component_evalCell_get
    if _newclass:
        evalCell = _swig_property(_or1kfsim.component_evalCell_get, _or1kfsim.component_evalCell_set)
component_swigregister = _or1kfsim.component_swigregister
component_swigregister(component)

class callback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callback, name)
    __repr__ = _swig_repr

    def __init__(self, handler: 'gv::callback_handle'):
        this = _or1kfsim.new_callback(handler)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def _exec(self) -> "void":
        return _or1kfsim.callback__exec(self)
    __swig_destroy__ = _or1kfsim.delete_callback
    __del__ = lambda self: None
callback_swigregister = _or1kfsim.callback_swigregister
callback_swigregister(callback)

class callbackFifo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callbackFifo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callbackFifo, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _or1kfsim.new_callbackFifo()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push(self, callback: 'callback') -> "void":
        return _or1kfsim.callbackFifo_push(self, callback)

    def pop(self) -> "gv::callback *":
        return _or1kfsim.callbackFifo_pop(self)

    def popAndExec(self) -> "void":
        return _or1kfsim.callbackFifo_popAndExec(self)
    __swig_destroy__ = _or1kfsim.delete_callbackFifo
    __del__ = lambda self: None
callbackFifo_swigregister = _or1kfsim.callbackFifo_swigregister
callbackFifo_swigregister(callbackFifo)


_or1kfsim.GV_IOREQ_ERROR_swigconstant(_or1kfsim)
GV_IOREQ_ERROR = _or1kfsim.GV_IOREQ_ERROR

_or1kfsim.GV_IOREQ_STALLED_swigconstant(_or1kfsim)
GV_IOREQ_STALLED = _or1kfsim.GV_IOREQ_STALLED

_or1kfsim.GV_IOREQ_NB_STALL_DATA_swigconstant(_or1kfsim)
GV_IOREQ_NB_STALL_DATA = _or1kfsim.GV_IOREQ_NB_STALL_DATA
class ioReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ioReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', addr: 'uint32_t', data: 'uint8_t *', size: 'uint32_t', isRead: 'bool'):
        this = _or1kfsim.new_ioReq(initiator, addr, data, size, isRead)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def getAddr(self) -> "uint32_t":
        return _or1kfsim.ioReq_getAddr(self)

    def setAddr(self, addr: 'uint32_t') -> "void":
        return _or1kfsim.ioReq_setAddr(self, addr)

    def getData(self) -> "uint8_t *":
        return _or1kfsim.ioReq_getData(self)

    def setData(self, data: 'uint8_t *') -> "void":
        return _or1kfsim.ioReq_setData(self, data)

    def getSize(self) -> "uint32_t":
        return _or1kfsim.ioReq_getSize(self)

    def setSize(self, size: 'uint32_t') -> "void":
        return _or1kfsim.ioReq_setSize(self, size)

    def getIsRead(self) -> "bool":
        return _or1kfsim.ioReq_getIsRead(self)

    def setIsRead(self, isRead: 'bool') -> "void":
        return _or1kfsim.ioReq_setIsRead(self, isRead)

    def setLatency(self, newLatency: 'int64_t') -> "void":
        return _or1kfsim.ioReq_setLatency(self, newLatency)

    def incLatency(self, incr: 'int64_t') -> "void":
        return _or1kfsim.ioReq_incLatency(self, incr)

    def setLength(self, newDuration: 'int64_t') -> "void":
        return _or1kfsim.ioReq_setLength(self, newDuration)

    def getStartCycles(self) -> "int64_t":
        return _or1kfsim.ioReq_getStartCycles(self)

    def getLatency(self) -> "int64_t":
        return _or1kfsim.ioReq_getLatency(self)

    def getLength(self) -> "int64_t":
        return _or1kfsim.ioReq_getLength(self)

    def getEndCycles(self) -> "int64_t":
        return _or1kfsim.ioReq_getEndCycles(self)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _or1kfsim.ioReq_switchEngine(self, engine)

    def getEngine(self) -> "engine *":
        return _or1kfsim.ioReq_getEngine(self)

    def setDebug(self, value: 'bool') -> "void":
        return _or1kfsim.ioReq_setDebug(self, value)

    def getDebug(self) -> "bool":
        return _or1kfsim.ioReq_getDebug(self)

    def setSecure(self, value: 'bool') -> "void":
        return _or1kfsim.ioReq_setSecure(self, value)

    def getSecure(self) -> "bool":
        return _or1kfsim.ioReq_getSecure(self)
    __swig_setmethods__["error"] = _or1kfsim.ioReq_error_set
    __swig_getmethods__["error"] = _or1kfsim.ioReq_error_get
    if _newclass:
        error = _swig_property(_or1kfsim.ioReq_error_get, _or1kfsim.ioReq_error_set)
    __swig_setmethods__["stallCallback"] = _or1kfsim.ioReq_stallCallback_set
    __swig_getmethods__["stallCallback"] = _or1kfsim.ioReq_stallCallback_get
    if _newclass:
        stallCallback = _swig_property(_or1kfsim.ioReq_stallCallback_get, _or1kfsim.ioReq_stallCallback_set)
    __swig_setmethods__["stallRetryCallback"] = _or1kfsim.ioReq_stallRetryCallback_set
    __swig_getmethods__["stallRetryCallback"] = _or1kfsim.ioReq_stallRetryCallback_get
    if _newclass:
        stallRetryCallback = _swig_property(_or1kfsim.ioReq_stallRetryCallback_get, _or1kfsim.ioReq_stallRetryCallback_set)
    __swig_setmethods__["stallData"] = _or1kfsim.ioReq_stallData_set
    __swig_getmethods__["stallData"] = _or1kfsim.ioReq_stallData_get
    if _newclass:
        stallData = _swig_property(_or1kfsim.ioReq_stallData_get, _or1kfsim.ioReq_stallData_set)
    __swig_setmethods__["next"] = _or1kfsim.ioReq_next_set
    __swig_getmethods__["next"] = _or1kfsim.ioReq_next_get
    if _newclass:
        next = _swig_property(_or1kfsim.ioReq_next_get, _or1kfsim.ioReq_next_set)
    __swig_destroy__ = _or1kfsim.delete_ioReq
    __del__ = lambda self: None
ioReq_swigregister = _or1kfsim.ioReq_swigregister
ioReq_swigregister(ioReq)

class ioSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ioSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_ioSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["ioReq"] = _or1kfsim.ioSlave_ioReq_set
    __swig_getmethods__["ioReq"] = _or1kfsim.ioSlave_ioReq_get
    if _newclass:
        ioReq = _swig_property(_or1kfsim.ioSlave_ioReq_get, _or1kfsim.ioSlave_ioReq_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.ioSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.ioSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.ioSlave_resyncTarget_get, _or1kfsim.ioSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.ioSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.ioSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.ioSlave_initiatorEngine_get, _or1kfsim.ioSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.ioSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.ioSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.ioSlave_targetEngine_get, _or1kfsim.ioSlave_targetEngine_set)

    def ioReqResync(self, req: 'ioReq') -> "bool":
        return _or1kfsim.ioSlave_ioReqResync(self, req)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.ioSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_ioSlave
    __del__ = lambda self: None
ioSlave_swigregister = _or1kfsim.ioSlave_swigregister
ioSlave_swigregister(ioSlave)

class combSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, combSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, combSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_combSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regMeth"] = _or1kfsim.combSlave_regMeth_set
    __swig_getmethods__["regMeth"] = _or1kfsim.combSlave_regMeth_get
    if _newclass:
        regMeth = _swig_property(_or1kfsim.combSlave_regMeth_get, _or1kfsim.combSlave_regMeth_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.combSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.combSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.combSlave_resyncTarget_get, _or1kfsim.combSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.combSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.combSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.combSlave_initiatorEngine_get, _or1kfsim.combSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.combSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.combSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.combSlave_targetEngine_get, _or1kfsim.combSlave_targetEngine_set)

    def regResync(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _or1kfsim.combSlave_regResync(self, outPort, data)

    def reg(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _or1kfsim.combSlave_reg(self, outPort, data)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.combSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_combSlave
    __del__ = lambda self: None
combSlave_swigregister = _or1kfsim.combSlave_swigregister
combSlave_swigregister(combSlave)

class bsReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bsReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', headerSize: 'int', dataSize: 'int', dataLen: 'int'=0):
        this = _or1kfsim.new_bsReq(initiator, headerSize, dataSize, dataLen)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_bsReq
    __del__ = lambda self: None

    def getIsRead(self) -> "bool":
        return _or1kfsim.bsReq_getIsRead(self)

    def getData(self) -> "uint8_t *":
        return _or1kfsim.bsReq_getData(self)

    def getDataHead(self) -> "int":
        return _or1kfsim.bsReq_getDataHead(self)

    def setDataHead(self, head: 'int') -> "void":
        return _or1kfsim.bsReq_setDataHead(self, head)

    def getHeader(self) -> "uint8_t *":
        return _or1kfsim.bsReq_getHeader(self)

    def setNext(self, req: 'bsReq') -> "void":
        return _or1kfsim.bsReq_setNext(self, req)

    def getNext(self) -> "gv::bsReq *":
        return _or1kfsim.bsReq_getNext(self)

    def getDataSize(self) -> "int":
        return _or1kfsim.bsReq_getDataSize(self)

    def getDataLen(self) -> "int":
        return _or1kfsim.bsReq_getDataLen(self)

    def setLatency(self, latency: 'int64_t') -> "void":
        return _or1kfsim.bsReq_setLatency(self, latency)

    def getLatency(self) -> "int64_t":
        return _or1kfsim.bsReq_getLatency(self)

    def setDataSize(self, _dataSize: 'int') -> "void":
        return _or1kfsim.bsReq_setDataSize(self, _dataSize)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _or1kfsim.bsReq_switchEngine(self, engine)
bsReq_swigregister = _or1kfsim.bsReq_swigregister
bsReq_swigregister(bsReq)

class bsSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, bsSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_bsSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["bsReqMeth"] = _or1kfsim.bsSlave_bsReqMeth_set
    __swig_getmethods__["bsReqMeth"] = _or1kfsim.bsSlave_bsReqMeth_get
    if _newclass:
        bsReqMeth = _swig_property(_or1kfsim.bsSlave_bsReqMeth_get, _or1kfsim.bsSlave_bsReqMeth_set)
    __swig_setmethods__["bsDataMeth"] = _or1kfsim.bsSlave_bsDataMeth_set
    __swig_getmethods__["bsDataMeth"] = _or1kfsim.bsSlave_bsDataMeth_get
    if _newclass:
        bsDataMeth = _swig_property(_or1kfsim.bsSlave_bsDataMeth_get, _or1kfsim.bsSlave_bsDataMeth_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.bsSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.bsSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.bsSlave_resyncTarget_get, _or1kfsim.bsSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.bsSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.bsSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.bsSlave_initiatorEngine_get, _or1kfsim.bsSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.bsSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.bsSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.bsSlave_targetEngine_get, _or1kfsim.bsSlave_targetEngine_set)

    def bsReqResync(self, req: 'bsReq') -> "bool":
        return _or1kfsim.bsSlave_bsReqResync(self, req)

    def bsDataResync(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _or1kfsim.bsSlave_bsDataResync(self, data, dataLen, latency)

    def bsReq(self, req: 'bsReq') -> "bool":
        return _or1kfsim.bsSlave_bsReq(self, req)

    def bsData(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _or1kfsim.bsSlave_bsData(self, data, dataLen, latency)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.bsSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_bsSlave
    __del__ = lambda self: None
bsSlave_swigregister = _or1kfsim.bsSlave_swigregister
bsSlave_swigregister(bsSlave)

class spiHeader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, spiHeader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, spiHeader, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cmd"] = _or1kfsim.spiHeader_cmd_set
    __swig_getmethods__["cmd"] = _or1kfsim.spiHeader_cmd_get
    if _newclass:
        cmd = _swig_property(_or1kfsim.spiHeader_cmd_get, _or1kfsim.spiHeader_cmd_set)
    __swig_setmethods__["addr"] = _or1kfsim.spiHeader_addr_set
    __swig_getmethods__["addr"] = _or1kfsim.spiHeader_addr_get
    if _newclass:
        addr = _swig_property(_or1kfsim.spiHeader_addr_get, _or1kfsim.spiHeader_addr_set)
    __swig_setmethods__["len"] = _or1kfsim.spiHeader_len_set
    __swig_getmethods__["len"] = _or1kfsim.spiHeader_len_get
    if _newclass:
        len = _swig_property(_or1kfsim.spiHeader_len_get, _or1kfsim.spiHeader_len_set)
    __swig_setmethods__["cs"] = _or1kfsim.spiHeader_cs_set
    __swig_getmethods__["cs"] = _or1kfsim.spiHeader_cs_get
    if _newclass:
        cs = _swig_property(_or1kfsim.spiHeader_cs_get, _or1kfsim.spiHeader_cs_set)

    def __init__(self):
        this = _or1kfsim.new_spiHeader()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_spiHeader
    __del__ = lambda self: None
spiHeader_swigregister = _or1kfsim.spiHeader_swigregister
spiHeader_swigregister(spiHeader)

class wireSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, wireSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, wireSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_wireSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["syncMeth"] = _or1kfsim.wireSlave_syncMeth_set
    __swig_getmethods__["syncMeth"] = _or1kfsim.wireSlave_syncMeth_get
    if _newclass:
        syncMeth = _swig_property(_or1kfsim.wireSlave_syncMeth_get, _or1kfsim.wireSlave_syncMeth_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.wireSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.wireSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.wireSlave_resyncTarget_get, _or1kfsim.wireSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.wireSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.wireSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.wireSlave_initiatorEngine_get, _or1kfsim.wireSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.wireSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.wireSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.wireSlave_targetEngine_get, _or1kfsim.wireSlave_targetEngine_set)

    def syncResync(self, value: 'uint32_t') -> "void":
        return _or1kfsim.wireSlave_syncResync(self, value)

    def sync(self, value: 'uint32_t') -> "void":
        return _or1kfsim.wireSlave_sync(self, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.wireSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_wireSlave
    __del__ = lambda self: None
wireSlave_swigregister = _or1kfsim.wireSlave_swigregister
wireSlave_swigregister(wireSlave)

class cpuCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cpuCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cpuCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_cpuCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccess"] = _or1kfsim.cpuCtrlSlave_regAccess_set
    __swig_getmethods__["regAccess"] = _or1kfsim.cpuCtrlSlave_regAccess_get
    if _newclass:
        regAccess = _swig_property(_or1kfsim.cpuCtrlSlave_regAccess_get, _or1kfsim.cpuCtrlSlave_regAccess_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.cpuCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.cpuCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.cpuCtrlSlave_resyncTarget_get, _or1kfsim.cpuCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.cpuCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.cpuCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.cpuCtrlSlave_initiatorEngine_get, _or1kfsim.cpuCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.cpuCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.cpuCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.cpuCtrlSlave_targetEngine_get, _or1kfsim.cpuCtrlSlave_targetEngine_set)

    def regAccessResync(self, reg: 'uint32_t', isRead: 'int', value: 'uint32_t *') -> "bool":
        return _or1kfsim.cpuCtrlSlave_regAccessResync(self, reg, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.cpuCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_cpuCtrlSlave
    __del__ = lambda self: None
cpuCtrlSlave_swigregister = _or1kfsim.cpuCtrlSlave_swigregister
cpuCtrlSlave_swigregister(cpuCtrlSlave)

class cacheCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cacheCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cacheCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_cacheCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["enable"] = _or1kfsim.cacheCtrlSlave_enable_set
    __swig_getmethods__["enable"] = _or1kfsim.cacheCtrlSlave_enable_get
    if _newclass:
        enable = _swig_property(_or1kfsim.cacheCtrlSlave_enable_get, _or1kfsim.cacheCtrlSlave_enable_set)
    __swig_setmethods__["flushAll"] = _or1kfsim.cacheCtrlSlave_flushAll_set
    __swig_getmethods__["flushAll"] = _or1kfsim.cacheCtrlSlave_flushAll_get
    if _newclass:
        flushAll = _swig_property(_or1kfsim.cacheCtrlSlave_flushAll_get, _or1kfsim.cacheCtrlSlave_flushAll_set)
    __swig_setmethods__["flushLine"] = _or1kfsim.cacheCtrlSlave_flushLine_set
    __swig_getmethods__["flushLine"] = _or1kfsim.cacheCtrlSlave_flushLine_get
    if _newclass:
        flushLine = _swig_property(_or1kfsim.cacheCtrlSlave_flushLine_get, _or1kfsim.cacheCtrlSlave_flushLine_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.cacheCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.cacheCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.cacheCtrlSlave_resyncTarget_get, _or1kfsim.cacheCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.cacheCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.cacheCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.cacheCtrlSlave_initiatorEngine_get, _or1kfsim.cacheCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.cacheCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.cacheCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.cacheCtrlSlave_targetEngine_get, _or1kfsim.cacheCtrlSlave_targetEngine_set)

    def enableResync(self, enable: 'bool') -> "void":
        return _or1kfsim.cacheCtrlSlave_enableResync(self, enable)

    def flushAllResync(self) -> "void":
        return _or1kfsim.cacheCtrlSlave_flushAllResync(self)

    def flushLineResync(self, addr: 'unsigned int') -> "void":
        return _or1kfsim.cacheCtrlSlave_flushLineResync(self, addr)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.cacheCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_cacheCtrlSlave
    __del__ = lambda self: None
cacheCtrlSlave_swigregister = _or1kfsim.cacheCtrlSlave_swigregister
cacheCtrlSlave_swigregister(cacheCtrlSlave)

class regSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, regSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, regSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _or1kfsim.new_regSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccessMeth"] = _or1kfsim.regSlave_regAccessMeth_set
    __swig_getmethods__["regAccessMeth"] = _or1kfsim.regSlave_regAccessMeth_get
    if _newclass:
        regAccessMeth = _swig_property(_or1kfsim.regSlave_regAccessMeth_get, _or1kfsim.regSlave_regAccessMeth_set)
    __swig_setmethods__["resyncTarget"] = _or1kfsim.regSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _or1kfsim.regSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_or1kfsim.regSlave_resyncTarget_get, _or1kfsim.regSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _or1kfsim.regSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _or1kfsim.regSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_or1kfsim.regSlave_initiatorEngine_get, _or1kfsim.regSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _or1kfsim.regSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _or1kfsim.regSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_or1kfsim.regSlave_targetEngine_get, _or1kfsim.regSlave_targetEngine_set)

    def regAccessResync(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _or1kfsim.regSlave_regAccessResync(self, slaveId, isRead, value)

    def regAccess(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _or1kfsim.regSlave_regAccess(self, slaveId, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _or1kfsim.regSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _or1kfsim.delete_regSlave
    __del__ = lambda self: None
regSlave_swigregister = _or1kfsim.regSlave_swigregister
regSlave_swigregister(regSlave)

class instrTrace_metric_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, instrTrace_metric_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, instrTrace_metric_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["isAbsolute"] = _or1kfsim.instrTrace_metric_t_isAbsolute_set
    __swig_getmethods__["isAbsolute"] = _or1kfsim.instrTrace_metric_t_isAbsolute_get
    if _newclass:
        isAbsolute = _swig_property(_or1kfsim.instrTrace_metric_t_isAbsolute_get, _or1kfsim.instrTrace_metric_t_isAbsolute_set)
    __swig_setmethods__["size"] = _or1kfsim.instrTrace_metric_t_size_set
    __swig_getmethods__["size"] = _or1kfsim.instrTrace_metric_t_size_get
    if _newclass:
        size = _swig_property(_or1kfsim.instrTrace_metric_t_size_get, _or1kfsim.instrTrace_metric_t_size_set)
    __swig_setmethods__["delay"] = _or1kfsim.instrTrace_metric_t_delay_set
    __swig_getmethods__["delay"] = _or1kfsim.instrTrace_metric_t_delay_get
    if _newclass:
        delay = _swig_property(_or1kfsim.instrTrace_metric_t_delay_get, _or1kfsim.instrTrace_metric_t_delay_set)

    def __init__(self):
        this = _or1kfsim.new_instrTrace_metric_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_instrTrace_metric_t
    __del__ = lambda self: None
instrTrace_metric_t_swigregister = _or1kfsim.instrTrace_metric_t_swigregister
instrTrace_metric_t_swigregister(instrTrace_metric_t)

class Or1k(component):
    __swig_setmethods__ = {}
    for _s in [component]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Or1k, name, value)
    __swig_getmethods__ = {}
    for _s in [component]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Or1k, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["or1ksimLibPath"] = _or1kfsim.Or1k_or1ksimLibPath_set
    __swig_getmethods__["or1ksimLibPath"] = _or1kfsim.Or1k_or1ksimLibPath_get
    if _newclass:
        or1ksimLibPath = _swig_property(_or1kfsim.Or1k_or1ksimLibPath_get, _or1kfsim.Or1k_or1ksimLibPath_set)
    __swig_setmethods__["coreId"] = _or1kfsim.Or1k_coreId_set
    __swig_getmethods__["coreId"] = _or1kfsim.Or1k_coreId_get
    if _newclass:
        coreId = _swig_property(_or1kfsim.Or1k_coreId_get, _or1kfsim.Or1k_coreId_set)
    __swig_setmethods__["clusterId"] = _or1kfsim.Or1k_clusterId_set
    __swig_getmethods__["clusterId"] = _or1kfsim.Or1k_clusterId_get
    if _newclass:
        clusterId = _swig_property(_or1kfsim.Or1k_clusterId_get, _or1kfsim.Or1k_clusterId_set)
    __swig_setmethods__["bootAddr"] = _or1kfsim.Or1k_bootAddr_set
    __swig_getmethods__["bootAddr"] = _or1kfsim.Or1k_bootAddr_get
    if _newclass:
        bootAddr = _swig_property(_or1kfsim.Or1k_bootAddr_get, _or1kfsim.Or1k_bootAddr_set)
    __swig_setmethods__["issTrace"] = _or1kfsim.Or1k_issTrace_set
    __swig_getmethods__["issTrace"] = _or1kfsim.Or1k_issTrace_get
    if _newclass:
        issTrace = _swig_property(_or1kfsim.Or1k_issTrace_get, _or1kfsim.Or1k_issTrace_set)
    __swig_setmethods__["dumpPc"] = _or1kfsim.Or1k_dumpPc_set
    __swig_getmethods__["dumpPc"] = _or1kfsim.Or1k_dumpPc_get
    if _newclass:
        dumpPc = _swig_property(_or1kfsim.Or1k_dumpPc_get, _or1kfsim.Or1k_dumpPc_set)
    __swig_setmethods__["dumpInstrTrace"] = _or1kfsim.Or1k_dumpInstrTrace_set
    __swig_getmethods__["dumpInstrTrace"] = _or1kfsim.Or1k_dumpInstrTrace_get
    if _newclass:
        dumpInstrTrace = _swig_property(_or1kfsim.Or1k_dumpInstrTrace_get, _or1kfsim.Or1k_dumpInstrTrace_set)
    __swig_setmethods__["pcache"] = _or1kfsim.Or1k_pcache_set
    __swig_getmethods__["pcache"] = _or1kfsim.Or1k_pcache_get
    if _newclass:
        pcache = _swig_property(_or1kfsim.Or1k_pcache_get, _or1kfsim.Or1k_pcache_set)
    __swig_setmethods__["pcacheNbWays"] = _or1kfsim.Or1k_pcacheNbWays_set
    __swig_getmethods__["pcacheNbWays"] = _or1kfsim.Or1k_pcacheNbWays_get
    if _newclass:
        pcacheNbWays = _swig_property(_or1kfsim.Or1k_pcacheNbWays_get, _or1kfsim.Or1k_pcacheNbWays_set)
    __swig_setmethods__["pcacheLineSize"] = _or1kfsim.Or1k_pcacheLineSize_set
    __swig_getmethods__["pcacheLineSize"] = _or1kfsim.Or1k_pcacheLineSize_get
    if _newclass:
        pcacheLineSize = _swig_property(_or1kfsim.Or1k_pcacheLineSize_get, _or1kfsim.Or1k_pcacheLineSize_set)
    __swig_setmethods__["pcacheNbSets"] = _or1kfsim.Or1k_pcacheNbSets_set
    __swig_getmethods__["pcacheNbSets"] = _or1kfsim.Or1k_pcacheNbSets_get
    if _newclass:
        pcacheNbSets = _swig_property(_or1kfsim.Or1k_pcacheNbSets_get, _or1kfsim.Or1k_pcacheNbSets_set)
    __swig_setmethods__["dcache"] = _or1kfsim.Or1k_dcache_set
    __swig_getmethods__["dcache"] = _or1kfsim.Or1k_dcache_get
    if _newclass:
        dcache = _swig_property(_or1kfsim.Or1k_dcache_get, _or1kfsim.Or1k_dcache_set)
    __swig_setmethods__["dcacheNbWays"] = _or1kfsim.Or1k_dcacheNbWays_set
    __swig_getmethods__["dcacheNbWays"] = _or1kfsim.Or1k_dcacheNbWays_get
    if _newclass:
        dcacheNbWays = _swig_property(_or1kfsim.Or1k_dcacheNbWays_get, _or1kfsim.Or1k_dcacheNbWays_set)
    __swig_setmethods__["dcacheLineSize"] = _or1kfsim.Or1k_dcacheLineSize_set
    __swig_getmethods__["dcacheLineSize"] = _or1kfsim.Or1k_dcacheLineSize_get
    if _newclass:
        dcacheLineSize = _swig_property(_or1kfsim.Or1k_dcacheLineSize_get, _or1kfsim.Or1k_dcacheLineSize_set)
    __swig_setmethods__["dcacheNbSets"] = _or1kfsim.Or1k_dcacheNbSets_set
    __swig_getmethods__["dcacheNbSets"] = _or1kfsim.Or1k_dcacheNbSets_get
    if _newclass:
        dcacheNbSets = _swig_property(_or1kfsim.Or1k_dcacheNbSets_get, _or1kfsim.Or1k_dcacheNbSets_set)
    __swig_setmethods__["isaSubsets"] = _or1kfsim.Or1k_isaSubsets_set
    __swig_getmethods__["isaSubsets"] = _or1kfsim.Or1k_isaSubsets_get
    if _newclass:
        isaSubsets = _swig_property(_or1kfsim.Or1k_isaSubsets_get, _or1kfsim.Or1k_isaSubsets_set)
    __swig_setmethods__["nbSharedFpu"] = _or1kfsim.Or1k_nbSharedFpu_set
    __swig_getmethods__["nbSharedFpu"] = _or1kfsim.Or1k_nbSharedFpu_get
    if _newclass:
        nbSharedFpu = _swig_property(_or1kfsim.Or1k_nbSharedFpu_get, _or1kfsim.Or1k_nbSharedFpu_set)
    __swig_setmethods__["power"] = _or1kfsim.Or1k_power_set
    __swig_getmethods__["power"] = _or1kfsim.Or1k_power_get
    if _newclass:
        power = _swig_property(_or1kfsim.Or1k_power_get, _or1kfsim.Or1k_power_set)
    __swig_setmethods__["autoboot"] = _or1kfsim.Or1k_autoboot_set
    __swig_getmethods__["autoboot"] = _or1kfsim.Or1k_autoboot_get
    if _newclass:
        autoboot = _swig_property(_or1kfsim.Or1k_autoboot_get, _or1kfsim.Or1k_autoboot_set)

    def build(self) -> "int":
        return _or1kfsim.Or1k_build(self)

    def start(self) -> "int":
        return _or1kfsim.Or1k_start(self)

    def semiHostingCallback(self, id: 'unsigned int', regs: 'unsigned int *') -> "uint64_t":
        return _or1kfsim.Or1k_semiHostingCallback(self, id, regs)

    def trapCallback(self, id: 'unsigned int', regs: 'unsigned int *') -> "uint64_t":
        return _or1kfsim.Or1k_trapCallback(self, id, regs)

    def eventCallback(self, id: 'int', value: 'unsigned int') -> "void":
        return _or1kfsim.Or1k_eventCallback(self, id, value)

    def exitCallback(self, exit: 'int') -> "void":
        return _or1kfsim.Or1k_exitCallback(self, exit)

    def counterCallback(self, id: 'int', counterVal: 'unsigned int *') -> "void":
        return _or1kfsim.Or1k_counterCallback(self, id, counterVal)

    def traceCallback(self, traceFile: 'FILE *', trace: 'char *', traceShort: 'char *') -> "void":
        return _or1kfsim.Or1k_traceCallback(self, traceFile, trace, traceShort)

    def fenceCallback(self, _latency: 'int *') -> "void":
        return _or1kfsim.Or1k_fenceCallback(self, _latency)

    def fetchCallback(self, addr: 'uint32_t', isRead: 'int', data: 'uint8_t *', size: 'int', _latency: 'int *') -> "int":
        return _or1kfsim.Or1k_fetchCallback(self, addr, isRead, data, size, _latency)

    def ioCallback(self, addr: 'uint32_t', isRead: 'int', data: 'uint8_t *', size: 'int', _latency: 'int *') -> "int":
        return _or1kfsim.Or1k_ioCallback(self, addr, isRead, data, size, _latency)

    def modeCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1k_modeCallback(self, mode)

    def pgtabCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1k_pgtabCallback(self, mode)

    def pvCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1k_pvCallback(self, mode)

    def regBinary(self, binary: 'char *') -> "void":
        return _or1kfsim.Or1k_regBinary(self, binary)

    def readyToShutdown(self, ready: 'bool') -> "void":
        return _or1kfsim.Or1k_readyToShutdown(self, ready)
    __swig_destroy__ = _or1kfsim.delete_Or1k
    __del__ = lambda self: None
Or1k_swigregister = _or1kfsim.Or1k_swigregister
Or1k_swigregister(Or1k)

class Or1kfsim(Or1k):
    __swig_setmethods__ = {}
    for _s in [Or1k]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Or1kfsim, name, value)
    __swig_getmethods__ = {}
    for _s in [Or1k]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Or1kfsim, name)
    __repr__ = _swig_repr

    def start(self) -> "int":
        return _or1kfsim.Or1kfsim_start(self)

    def modeCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1kfsim_modeCallback(self, mode)

    def pgtabCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1kfsim_pgtabCallback(self, mode)

    def pvCallback(self, mode: 'unsigned int') -> "void":
        return _or1kfsim.Or1kfsim_pvCallback(self, mode)

    def __init__(self):
        this = _or1kfsim.new_Or1kfsim()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _or1kfsim.delete_Or1kfsim
    __del__ = lambda self: None
Or1kfsim_swigregister = _or1kfsim.Or1kfsim_swigregister
Or1kfsim_swigregister(Or1kfsim)

# This file is compatible with both classic and new-style classes.


