# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hwce_v4', [dirname(__file__)])
        except ImportError:
            import _hwce_v4
            return _hwce_v4
        if fp is not None:
            try:
                _mod = imp.load_module('_hwce_v4', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hwce_v4 = swig_import_helper()
    del swig_import_helper
else:
    import _hwce_v4
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class trace(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, trace, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, trace, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _hwce_v4.new_trace()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["isActive"] = _hwce_v4.trace_isActive_set
    __swig_getmethods__["isActive"] = _hwce_v4.trace_isActive_get
    if _newclass:
        isActive = _swig_property(_hwce_v4.trace_isActive_get, _hwce_v4.trace_isActive_set)
    __swig_setmethods__["path"] = _hwce_v4.trace_path_set
    __swig_getmethods__["path"] = _hwce_v4.trace_path_get
    if _newclass:
        path = _swig_property(_hwce_v4.trace_path_get, _hwce_v4.trace_path_set)

    def dumpMsg(self, fmt: 'char const *') -> "void":
        return _hwce_v4.trace_dumpMsg(self, fmt)

    def dumpUserMsg(self, fmt: 'char const *') -> "void":
        return _hwce_v4.trace_dumpUserMsg(self, fmt)

    def dumpWarning(self, fmt: 'char const *') -> "void":
        return _hwce_v4.trace_dumpWarning(self, fmt)

    def setComponent(self, comp: 'component') -> "void":
        return _hwce_v4.trace_setComponent(self, comp)
    __swig_destroy__ = _hwce_v4.delete_trace
    __del__ = lambda self: None
trace_swigregister = _hwce_v4.trace_swigregister
trace_swigregister(trace)

class slavePort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, slavePort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, slavePort, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _hwce_v4.new_slavePort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_slavePort
    __del__ = lambda self: None

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.slavePort_getSlavePortResync(self, initiatorEngine, targetEngine)

    def setName(self, name: 'string') -> "void":
        return _hwce_v4.slavePort_setName(self, name)

    def setComp(self, comp: 'component') -> "void":
        return _hwce_v4.slavePort_setComp(self, comp)

    def getPortClass(self) -> "unsigned long long":
        return _hwce_v4.slavePort_getPortClass(self)
    __swig_setmethods__["comp"] = _hwce_v4.slavePort_comp_set
    __swig_getmethods__["comp"] = _hwce_v4.slavePort_comp_get
    if _newclass:
        comp = _swig_property(_hwce_v4.slavePort_comp_get, _hwce_v4.slavePort_comp_set)
    __swig_setmethods__["name"] = _hwce_v4.slavePort_name_set
    __swig_getmethods__["name"] = _hwce_v4.slavePort_name_get
    if _newclass:
        name = _swig_property(_hwce_v4.slavePort_name_get, _hwce_v4.slavePort_name_set)

    def getName(self) -> "char *":
        return _hwce_v4.slavePort_getName(self)
    __swig_setmethods__["next"] = _hwce_v4.slavePort_next_set
    __swig_getmethods__["next"] = _hwce_v4.slavePort_next_get
    if _newclass:
        next = _swig_property(_hwce_v4.slavePort_next_get, _hwce_v4.slavePort_next_set)
    __swig_setmethods__["slaveId"] = _hwce_v4.slavePort_slaveId_set
    __swig_getmethods__["slaveId"] = _hwce_v4.slavePort_slaveId_get
    if _newclass:
        slaveId = _swig_property(_hwce_v4.slavePort_slaveId_get, _hwce_v4.slavePort_slaveId_set)
slavePort_swigregister = _hwce_v4.slavePort_swigregister
slavePort_swigregister(slavePort)

class inPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, inPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, inPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _hwce_v4.inPort_data_set
    __swig_getmethods__["data"] = _hwce_v4.inPort_data_get
    if _newclass:
        data = _swig_property(_hwce_v4.inPort_data_get, _hwce_v4.inPort_data_set)
    __swig_setmethods__["comp"] = _hwce_v4.inPort_comp_set
    __swig_getmethods__["comp"] = _hwce_v4.inPort_comp_get
    if _newclass:
        comp = _swig_property(_hwce_v4.inPort_comp_get, _hwce_v4.inPort_comp_set)
    __swig_setmethods__["targetComp"] = _hwce_v4.inPort_targetComp_set
    __swig_getmethods__["targetComp"] = _hwce_v4.inPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_hwce_v4.inPort_targetComp_get, _hwce_v4.inPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _hwce_v4.inPort_targetEval_set
    __swig_getmethods__["targetEval"] = _hwce_v4.inPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_hwce_v4.inPort_targetEval_get, _hwce_v4.inPort_targetEval_set)
    __swig_setmethods__["widthWords"] = _hwce_v4.inPort_widthWords_set
    __swig_getmethods__["widthWords"] = _hwce_v4.inPort_widthWords_get
    if _newclass:
        widthWords = _swig_property(_hwce_v4.inPort_widthWords_get, _hwce_v4.inPort_widthWords_set)

    def checkTarget(self) -> "void":
        return _hwce_v4.inPort_checkTarget(self)

    def read32(self) -> "uint32_t":
        return _hwce_v4.inPort_read32(self)

    def readAt(self, wordIndex: 'int') -> "uint32_t":
        return _hwce_v4.inPort_readAt(self, wordIndex)

    def copy(self, data: 'uint32_t *') -> "void":
        return _hwce_v4.inPort_copy(self, data)

    def __init__(self):
        this = _hwce_v4.new_inPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_inPort
    __del__ = lambda self: None
inPort_swigregister = _hwce_v4.inPort_swigregister
inPort_swigregister(inPort)

class outPort(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, outPort, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, outPort, name)
    __repr__ = _swig_repr
    __swig_setmethods__["port"] = _hwce_v4.outPort_port_set
    __swig_getmethods__["port"] = _hwce_v4.outPort_port_get
    if _newclass:
        port = _swig_property(_hwce_v4.outPort_port_get, _hwce_v4.outPort_port_set)
    __swig_setmethods__["data"] = _hwce_v4.outPort_data_set
    __swig_getmethods__["data"] = _hwce_v4.outPort_data_get
    if _newclass:
        data = _swig_property(_hwce_v4.outPort_data_get, _hwce_v4.outPort_data_set)
    __swig_setmethods__["ioId"] = _hwce_v4.outPort_ioId_set
    __swig_getmethods__["ioId"] = _hwce_v4.outPort_ioId_get
    if _newclass:
        ioId = _swig_property(_hwce_v4.outPort_ioId_get, _hwce_v4.outPort_ioId_set)
    __swig_setmethods__["comp"] = _hwce_v4.outPort_comp_set
    __swig_getmethods__["comp"] = _hwce_v4.outPort_comp_get
    if _newclass:
        comp = _swig_property(_hwce_v4.outPort_comp_get, _hwce_v4.outPort_comp_set)
    __swig_setmethods__["targetIoId"] = _hwce_v4.outPort_targetIoId_set
    __swig_getmethods__["targetIoId"] = _hwce_v4.outPort_targetIoId_get
    if _newclass:
        targetIoId = _swig_property(_hwce_v4.outPort_targetIoId_get, _hwce_v4.outPort_targetIoId_set)
    __swig_setmethods__["targetComp"] = _hwce_v4.outPort_targetComp_set
    __swig_getmethods__["targetComp"] = _hwce_v4.outPort_targetComp_get
    if _newclass:
        targetComp = _swig_property(_hwce_v4.outPort_targetComp_get, _hwce_v4.outPort_targetComp_set)
    __swig_setmethods__["targetEval"] = _hwce_v4.outPort_targetEval_set
    __swig_getmethods__["targetEval"] = _hwce_v4.outPort_targetEval_get
    if _newclass:
        targetEval = _swig_property(_hwce_v4.outPort_targetEval_get, _hwce_v4.outPort_targetEval_set)
    __swig_setmethods__["updated"] = _hwce_v4.outPort_updated_set
    __swig_getmethods__["updated"] = _hwce_v4.outPort_updated_get
    if _newclass:
        updated = _swig_property(_hwce_v4.outPort_updated_get, _hwce_v4.outPort_updated_set)

    def checkTarget(self) -> "void":
        return _hwce_v4.outPort_checkTarget(self)

    def write32(self, value: 'uint32_t') -> "void":
        return _hwce_v4.outPort_write32(self, value)

    def __init__(self):
        this = _hwce_v4.new_outPort()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_outPort
    __del__ = lambda self: None
outPort_swigregister = _hwce_v4.outPort_swigregister
outPort_swigregister(outPort)

class combRegInit(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, combRegInit, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, combRegInit, name)
    __repr__ = _swig_repr

    def __init__(self, port: 'outPort', data: 'uint32_t *'):
        this = _hwce_v4.new_combRegInit(port, data)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["port"] = _hwce_v4.combRegInit_port_set
    __swig_getmethods__["port"] = _hwce_v4.combRegInit_port_get
    if _newclass:
        port = _swig_property(_hwce_v4.combRegInit_port_get, _hwce_v4.combRegInit_port_set)
    __swig_setmethods__["data"] = _hwce_v4.combRegInit_data_set
    __swig_getmethods__["data"] = _hwce_v4.combRegInit_data_get
    if _newclass:
        data = _swig_property(_hwce_v4.combRegInit_data_get, _hwce_v4.combRegInit_data_set)
    __swig_destroy__ = _hwce_v4.delete_combRegInit
    __del__ = lambda self: None
combRegInit_swigregister = _hwce_v4.combRegInit_swigregister
combRegInit_swigregister(combRegInit)

class component(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, component, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, component, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _hwce_v4.new_component()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def setEngine(self, engineInstance: 'unsigned long') -> "void":
        return _hwce_v4.component_setEngine(self, engineInstance)

    def build(self) -> "int":
        return _hwce_v4.component_build(self)

    def start(self) -> "int":
        return _hwce_v4.component_start(self)

    def reset(self) -> "void":
        return _hwce_v4.component_reset(self)

    def close(self) -> "void":
        return _hwce_v4.component_close(self)
    __swig_destroy__ = _hwce_v4.delete_component
    __del__ = lambda self: None

    def state(self, name: 'char *') -> "void":
        return _hwce_v4.component_state(self, name)

    def memDump(self, base: 'unsigned int', size: 'unsigned int') -> "bool":
        return _hwce_v4.component_memDump(self, base, size)

    def getCycles(self) -> "int64_t":
        return _hwce_v4.component_getCycles(self)

    def disAllBkp(self) -> "void":
        return _hwce_v4.component_disAllBkp(self)

    def setBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int') -> "void":
        return _hwce_v4.component_setBkp(self, base, size, access)

    def checkBkp(self, base: 'unsigned int', size: 'unsigned int', access: 'unsigned int', matchAddr: 'unsigned int &', matchAccess: 'unsigned int &') -> "bool":
        return _hwce_v4.component_checkBkp(self, base, size, access, matchAddr, matchAccess)

    def reg(self, outPort: 'outPort', data: 'uint32_t *', localData: 'uint32_t **', inPort: 'inPort') -> "void":
        return _hwce_v4.component_reg(self, outPort, data, localData, inPort)

    def regOut(self, name: 'string', port: 'outPort') -> "void":
        return _hwce_v4.component_regOut(self, name, port)

    def regIn(self, *args) -> "void":
        return _hwce_v4.component_regIn(self, *args)

    def evalNetwork(self) -> "void":
        return _hwce_v4.component_evalNetwork(self)

    def commitNetwork(self) -> "void":
        return _hwce_v4.component_commitNetwork(self)

    def setNetwork(self, network: 'component') -> "void":
        return _hwce_v4.component_setNetwork(self, network)

    def eval(self) -> "void":
        return _hwce_v4.component_eval(self)

    def precommit(self) -> "void":
        return _hwce_v4.component_precommit(self)

    def commit(self) -> "void":
        return _hwce_v4.component_commit(self)

    def syncNextCycle(self, *args) -> "void":
        return _hwce_v4.component_syncNextCycle(self, *args)

    def syncOut(self, *args) -> "void":
        return _hwce_v4.component_syncOut(self, *args)

    def addCell(self, comp: 'component') -> "void":
        return _hwce_v4.component_addCell(self, comp)

    def connectNetworkOutputs(self) -> "void":
        return _hwce_v4.component_connectNetworkOutputs(self)

    def regSlave(self, name: 'string', port: 'slavePort') -> "void":
        return _hwce_v4.component_regSlave(self, name, port)

    def registerPowerTrace(self, trace: 'gv::powerTrace **', name: 'char *') -> "bool":
        return _hwce_v4.component_registerPowerTrace(self, trace, name)

    def confPowerTrace(self, trace: 'gv::powerTrace *') -> "void":
        return _hwce_v4.component_confPowerTrace(self, trace)

    def confVcdTrace(self, trace: 'gv::vcdTrace *', path: 'char const *', isActive: 'bool', file: 'long') -> "void":
        return _hwce_v4.component_confVcdTrace(self, trace, path, isActive, file)

    def getSlavePort(self, name: 'char *') -> "gv::slavePort *":
        return _hwce_v4.component_getSlavePort(self, name)

    def getSlavePortResync(self, initiatorEngine: 'unsigned long long', port: 'slavePort') -> "gv::slavePort *":
        return _hwce_v4.component_getSlavePortResync(self, initiatorEngine, port)

    def regMaster(self, name: 'string', port: 'gv::masterPort *') -> "void":
        return _hwce_v4.component_regMaster(self, name, port)

    def getMasterName(self, index: 'unsigned int') -> "char const *":
        return _hwce_v4.component_getMasterName(self, index)

    def getSlaveName(self, index: 'unsigned int') -> "char const *":
        return _hwce_v4.component_getSlaveName(self, index)

    def getTrace(self, name: 'char const *') -> "gv::trace *":
        return _hwce_v4.component_getTrace(self, name)

    def getVcdTrace(self, name: 'char const *') -> "gv::vcdTrace *":
        return _hwce_v4.component_getVcdTrace(self, name)

    def getTraceName(self, index: 'unsigned int') -> "char const *":
        return _hwce_v4.component_getTraceName(self, index)

    def getVcdTraceName(self, index: 'unsigned int') -> "char const *":
        return _hwce_v4.component_getVcdTraceName(self, index)

    def linkMasterTo(self, name: 'char const *', slavePort: 'slavePort') -> "void":
        return _hwce_v4.component_linkMasterTo(self, name, slavePort)

    def regTrace(self, name: 'string', tr: 'trace') -> "void":
        return _hwce_v4.component_regTrace(self, name, tr)

    def regVcd(self, name: 'string', vcd: 'gv::vcdTrace *', width: 'int') -> "void":
        return _hwce_v4.component_regVcd(self, name, vcd, width)

    def regVcdString(self, name: 'string', vcd: 'gv::vcdTrace *') -> "void":
        return _hwce_v4.component_regVcdString(self, name, vcd)

    def getUserTrace(self) -> "gv::trace *":
        return _hwce_v4.component_getUserTrace(self)

    def getEngine(self) -> "engine *":
        return _hwce_v4.component_getEngine(self)

    def getPowerEngine(self) -> "gv::powerEngine *":
        return _hwce_v4.component_getPowerEngine(self)

    def confTrace(self, name: 'char const *', path: 'char const *', active: 'bool') -> "void":
        return _hwce_v4.component_confTrace(self, name, path, active)

    def reorderCell(self, nextComp: 'component') -> "void":
        return _hwce_v4.component_reorderCell(self, nextComp)

    def dequeueCell(self) -> "void":
        return _hwce_v4.component_dequeueCell(self)
    __swig_setmethods__["network"] = _hwce_v4.component_network_set
    __swig_getmethods__["network"] = _hwce_v4.component_network_get
    if _newclass:
        network = _swig_property(_hwce_v4.component_network_get, _hwce_v4.component_network_set)
    __swig_setmethods__["evaluated"] = _hwce_v4.component_evaluated_set
    __swig_getmethods__["evaluated"] = _hwce_v4.component_evaluated_get
    if _newclass:
        evaluated = _swig_property(_hwce_v4.component_evaluated_get, _hwce_v4.component_evaluated_set)
    __swig_setmethods__["path"] = _hwce_v4.component_path_set
    __swig_getmethods__["path"] = _hwce_v4.component_path_get
    if _newclass:
        path = _swig_property(_hwce_v4.component_path_get, _hwce_v4.component_path_set)
    __swig_setmethods__["evalCell"] = _hwce_v4.component_evalCell_set
    __swig_getmethods__["evalCell"] = _hwce_v4.component_evalCell_get
    if _newclass:
        evalCell = _swig_property(_hwce_v4.component_evalCell_get, _hwce_v4.component_evalCell_set)
component_swigregister = _hwce_v4.component_swigregister
component_swigregister(component)

class callback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callback, name)
    __repr__ = _swig_repr

    def __init__(self, handler: 'gv::callback_handle'):
        this = _hwce_v4.new_callback(handler)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def _exec(self) -> "void":
        return _hwce_v4.callback__exec(self)
    __swig_destroy__ = _hwce_v4.delete_callback
    __del__ = lambda self: None
callback_swigregister = _hwce_v4.callback_swigregister
callback_swigregister(callback)

class callbackFifo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, callbackFifo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, callbackFifo, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _hwce_v4.new_callbackFifo()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push(self, callback: 'callback') -> "void":
        return _hwce_v4.callbackFifo_push(self, callback)

    def pop(self) -> "gv::callback *":
        return _hwce_v4.callbackFifo_pop(self)

    def popAndExec(self) -> "void":
        return _hwce_v4.callbackFifo_popAndExec(self)
    __swig_destroy__ = _hwce_v4.delete_callbackFifo
    __del__ = lambda self: None
callbackFifo_swigregister = _hwce_v4.callbackFifo_swigregister
callbackFifo_swigregister(callbackFifo)


_hwce_v4.GV_IOREQ_ERROR_swigconstant(_hwce_v4)
GV_IOREQ_ERROR = _hwce_v4.GV_IOREQ_ERROR

_hwce_v4.GV_IOREQ_STALLED_swigconstant(_hwce_v4)
GV_IOREQ_STALLED = _hwce_v4.GV_IOREQ_STALLED

_hwce_v4.GV_IOREQ_NB_STALL_DATA_swigconstant(_hwce_v4)
GV_IOREQ_NB_STALL_DATA = _hwce_v4.GV_IOREQ_NB_STALL_DATA
class ioReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ioReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', addr: 'uint32_t', data: 'uint8_t *', size: 'uint32_t', isRead: 'bool'):
        this = _hwce_v4.new_ioReq(initiator, addr, data, size, isRead)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def getAddr(self) -> "uint32_t":
        return _hwce_v4.ioReq_getAddr(self)

    def setAddr(self, addr: 'uint32_t') -> "void":
        return _hwce_v4.ioReq_setAddr(self, addr)

    def getData(self) -> "uint8_t *":
        return _hwce_v4.ioReq_getData(self)

    def setData(self, data: 'uint8_t *') -> "void":
        return _hwce_v4.ioReq_setData(self, data)

    def getSize(self) -> "uint32_t":
        return _hwce_v4.ioReq_getSize(self)

    def setSize(self, size: 'uint32_t') -> "void":
        return _hwce_v4.ioReq_setSize(self, size)

    def getIsRead(self) -> "bool":
        return _hwce_v4.ioReq_getIsRead(self)

    def setIsRead(self, isRead: 'bool') -> "void":
        return _hwce_v4.ioReq_setIsRead(self, isRead)

    def setLatency(self, newLatency: 'int64_t') -> "void":
        return _hwce_v4.ioReq_setLatency(self, newLatency)

    def incLatency(self, incr: 'int64_t') -> "void":
        return _hwce_v4.ioReq_incLatency(self, incr)

    def setLength(self, newDuration: 'int64_t') -> "void":
        return _hwce_v4.ioReq_setLength(self, newDuration)

    def getStartCycles(self) -> "int64_t":
        return _hwce_v4.ioReq_getStartCycles(self)

    def getLatency(self) -> "int64_t":
        return _hwce_v4.ioReq_getLatency(self)

    def getLength(self) -> "int64_t":
        return _hwce_v4.ioReq_getLength(self)

    def getEndCycles(self) -> "int64_t":
        return _hwce_v4.ioReq_getEndCycles(self)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _hwce_v4.ioReq_switchEngine(self, engine)

    def getEngine(self) -> "engine *":
        return _hwce_v4.ioReq_getEngine(self)

    def setDebug(self, value: 'bool') -> "void":
        return _hwce_v4.ioReq_setDebug(self, value)

    def getDebug(self) -> "bool":
        return _hwce_v4.ioReq_getDebug(self)

    def setSecure(self, value: 'bool') -> "void":
        return _hwce_v4.ioReq_setSecure(self, value)

    def getSecure(self) -> "bool":
        return _hwce_v4.ioReq_getSecure(self)
    __swig_setmethods__["error"] = _hwce_v4.ioReq_error_set
    __swig_getmethods__["error"] = _hwce_v4.ioReq_error_get
    if _newclass:
        error = _swig_property(_hwce_v4.ioReq_error_get, _hwce_v4.ioReq_error_set)
    __swig_setmethods__["stallCallback"] = _hwce_v4.ioReq_stallCallback_set
    __swig_getmethods__["stallCallback"] = _hwce_v4.ioReq_stallCallback_get
    if _newclass:
        stallCallback = _swig_property(_hwce_v4.ioReq_stallCallback_get, _hwce_v4.ioReq_stallCallback_set)
    __swig_setmethods__["stallRetryCallback"] = _hwce_v4.ioReq_stallRetryCallback_set
    __swig_getmethods__["stallRetryCallback"] = _hwce_v4.ioReq_stallRetryCallback_get
    if _newclass:
        stallRetryCallback = _swig_property(_hwce_v4.ioReq_stallRetryCallback_get, _hwce_v4.ioReq_stallRetryCallback_set)
    __swig_setmethods__["stallData"] = _hwce_v4.ioReq_stallData_set
    __swig_getmethods__["stallData"] = _hwce_v4.ioReq_stallData_get
    if _newclass:
        stallData = _swig_property(_hwce_v4.ioReq_stallData_get, _hwce_v4.ioReq_stallData_set)
    __swig_setmethods__["next"] = _hwce_v4.ioReq_next_set
    __swig_getmethods__["next"] = _hwce_v4.ioReq_next_get
    if _newclass:
        next = _swig_property(_hwce_v4.ioReq_next_get, _hwce_v4.ioReq_next_set)
    __swig_destroy__ = _hwce_v4.delete_ioReq
    __del__ = lambda self: None
ioReq_swigregister = _hwce_v4.ioReq_swigregister
ioReq_swigregister(ioReq)

class ioSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ioSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ioSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_ioSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["ioReq"] = _hwce_v4.ioSlave_ioReq_set
    __swig_getmethods__["ioReq"] = _hwce_v4.ioSlave_ioReq_get
    if _newclass:
        ioReq = _swig_property(_hwce_v4.ioSlave_ioReq_get, _hwce_v4.ioSlave_ioReq_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.ioSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.ioSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.ioSlave_resyncTarget_get, _hwce_v4.ioSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.ioSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.ioSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.ioSlave_initiatorEngine_get, _hwce_v4.ioSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.ioSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.ioSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.ioSlave_targetEngine_get, _hwce_v4.ioSlave_targetEngine_set)

    def ioReqResync(self, req: 'ioReq') -> "bool":
        return _hwce_v4.ioSlave_ioReqResync(self, req)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.ioSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_ioSlave
    __del__ = lambda self: None
ioSlave_swigregister = _hwce_v4.ioSlave_swigregister
ioSlave_swigregister(ioSlave)

class combSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, combSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, combSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_combSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regMeth"] = _hwce_v4.combSlave_regMeth_set
    __swig_getmethods__["regMeth"] = _hwce_v4.combSlave_regMeth_get
    if _newclass:
        regMeth = _swig_property(_hwce_v4.combSlave_regMeth_get, _hwce_v4.combSlave_regMeth_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.combSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.combSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.combSlave_resyncTarget_get, _hwce_v4.combSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.combSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.combSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.combSlave_initiatorEngine_get, _hwce_v4.combSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.combSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.combSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.combSlave_targetEngine_get, _hwce_v4.combSlave_targetEngine_set)

    def regResync(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _hwce_v4.combSlave_regResync(self, outPort, data)

    def reg(self, outPort: 'outPort', data: 'uint32_t *') -> "void":
        return _hwce_v4.combSlave_reg(self, outPort, data)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.combSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_combSlave
    __del__ = lambda self: None
combSlave_swigregister = _hwce_v4.combSlave_swigregister
combSlave_swigregister(combSlave)

class bsReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bsReq, name)
    __repr__ = _swig_repr

    def __init__(self, initiator: 'component', headerSize: 'int', dataSize: 'int', dataLen: 'int'=0):
        this = _hwce_v4.new_bsReq(initiator, headerSize, dataSize, dataLen)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_bsReq
    __del__ = lambda self: None

    def getIsRead(self) -> "bool":
        return _hwce_v4.bsReq_getIsRead(self)

    def getData(self) -> "uint8_t *":
        return _hwce_v4.bsReq_getData(self)

    def getDataHead(self) -> "int":
        return _hwce_v4.bsReq_getDataHead(self)

    def setDataHead(self, head: 'int') -> "void":
        return _hwce_v4.bsReq_setDataHead(self, head)

    def getHeader(self) -> "uint8_t *":
        return _hwce_v4.bsReq_getHeader(self)

    def setNext(self, req: 'bsReq') -> "void":
        return _hwce_v4.bsReq_setNext(self, req)

    def getNext(self) -> "gv::bsReq *":
        return _hwce_v4.bsReq_getNext(self)

    def getDataSize(self) -> "int":
        return _hwce_v4.bsReq_getDataSize(self)

    def getDataLen(self) -> "int":
        return _hwce_v4.bsReq_getDataLen(self)

    def setLatency(self, latency: 'int64_t') -> "void":
        return _hwce_v4.bsReq_setLatency(self, latency)

    def getLatency(self) -> "int64_t":
        return _hwce_v4.bsReq_getLatency(self)

    def setDataSize(self, _dataSize: 'int') -> "void":
        return _hwce_v4.bsReq_setDataSize(self, _dataSize)

    def switchEngine(self, engine: 'gv::clockEngine *') -> "void":
        return _hwce_v4.bsReq_switchEngine(self, engine)
bsReq_swigregister = _hwce_v4.bsReq_swigregister
bsReq_swigregister(bsReq)

class bsSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, bsSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, bsSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_bsSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["bsReqMeth"] = _hwce_v4.bsSlave_bsReqMeth_set
    __swig_getmethods__["bsReqMeth"] = _hwce_v4.bsSlave_bsReqMeth_get
    if _newclass:
        bsReqMeth = _swig_property(_hwce_v4.bsSlave_bsReqMeth_get, _hwce_v4.bsSlave_bsReqMeth_set)
    __swig_setmethods__["bsDataMeth"] = _hwce_v4.bsSlave_bsDataMeth_set
    __swig_getmethods__["bsDataMeth"] = _hwce_v4.bsSlave_bsDataMeth_get
    if _newclass:
        bsDataMeth = _swig_property(_hwce_v4.bsSlave_bsDataMeth_get, _hwce_v4.bsSlave_bsDataMeth_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.bsSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.bsSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.bsSlave_resyncTarget_get, _hwce_v4.bsSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.bsSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.bsSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.bsSlave_initiatorEngine_get, _hwce_v4.bsSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.bsSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.bsSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.bsSlave_targetEngine_get, _hwce_v4.bsSlave_targetEngine_set)

    def bsReqResync(self, req: 'bsReq') -> "bool":
        return _hwce_v4.bsSlave_bsReqResync(self, req)

    def bsDataResync(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _hwce_v4.bsSlave_bsDataResync(self, data, dataLen, latency)

    def bsReq(self, req: 'bsReq') -> "bool":
        return _hwce_v4.bsSlave_bsReq(self, req)

    def bsData(self, data: 'uint8_t *', dataLen: 'unsigned int', latency: 'int64_t *') -> "void":
        return _hwce_v4.bsSlave_bsData(self, data, dataLen, latency)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.bsSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_bsSlave
    __del__ = lambda self: None
bsSlave_swigregister = _hwce_v4.bsSlave_swigregister
bsSlave_swigregister(bsSlave)

class spiHeader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, spiHeader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, spiHeader, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cmd"] = _hwce_v4.spiHeader_cmd_set
    __swig_getmethods__["cmd"] = _hwce_v4.spiHeader_cmd_get
    if _newclass:
        cmd = _swig_property(_hwce_v4.spiHeader_cmd_get, _hwce_v4.spiHeader_cmd_set)
    __swig_setmethods__["addr"] = _hwce_v4.spiHeader_addr_set
    __swig_getmethods__["addr"] = _hwce_v4.spiHeader_addr_get
    if _newclass:
        addr = _swig_property(_hwce_v4.spiHeader_addr_get, _hwce_v4.spiHeader_addr_set)
    __swig_setmethods__["len"] = _hwce_v4.spiHeader_len_set
    __swig_getmethods__["len"] = _hwce_v4.spiHeader_len_get
    if _newclass:
        len = _swig_property(_hwce_v4.spiHeader_len_get, _hwce_v4.spiHeader_len_set)
    __swig_setmethods__["cs"] = _hwce_v4.spiHeader_cs_set
    __swig_getmethods__["cs"] = _hwce_v4.spiHeader_cs_get
    if _newclass:
        cs = _swig_property(_hwce_v4.spiHeader_cs_get, _hwce_v4.spiHeader_cs_set)

    def __init__(self):
        this = _hwce_v4.new_spiHeader()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_spiHeader
    __del__ = lambda self: None
spiHeader_swigregister = _hwce_v4.spiHeader_swigregister
spiHeader_swigregister(spiHeader)

class wireSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, wireSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, wireSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_wireSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["syncMeth"] = _hwce_v4.wireSlave_syncMeth_set
    __swig_getmethods__["syncMeth"] = _hwce_v4.wireSlave_syncMeth_get
    if _newclass:
        syncMeth = _swig_property(_hwce_v4.wireSlave_syncMeth_get, _hwce_v4.wireSlave_syncMeth_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.wireSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.wireSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.wireSlave_resyncTarget_get, _hwce_v4.wireSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.wireSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.wireSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.wireSlave_initiatorEngine_get, _hwce_v4.wireSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.wireSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.wireSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.wireSlave_targetEngine_get, _hwce_v4.wireSlave_targetEngine_set)

    def syncResync(self, value: 'uint32_t') -> "void":
        return _hwce_v4.wireSlave_syncResync(self, value)

    def sync(self, value: 'uint32_t') -> "void":
        return _hwce_v4.wireSlave_sync(self, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.wireSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_wireSlave
    __del__ = lambda self: None
wireSlave_swigregister = _hwce_v4.wireSlave_swigregister
wireSlave_swigregister(wireSlave)

class cpuCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cpuCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cpuCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_cpuCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccess"] = _hwce_v4.cpuCtrlSlave_regAccess_set
    __swig_getmethods__["regAccess"] = _hwce_v4.cpuCtrlSlave_regAccess_get
    if _newclass:
        regAccess = _swig_property(_hwce_v4.cpuCtrlSlave_regAccess_get, _hwce_v4.cpuCtrlSlave_regAccess_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.cpuCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.cpuCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.cpuCtrlSlave_resyncTarget_get, _hwce_v4.cpuCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.cpuCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.cpuCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.cpuCtrlSlave_initiatorEngine_get, _hwce_v4.cpuCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.cpuCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.cpuCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.cpuCtrlSlave_targetEngine_get, _hwce_v4.cpuCtrlSlave_targetEngine_set)

    def regAccessResync(self, reg: 'uint32_t', isRead: 'int', value: 'uint32_t *') -> "bool":
        return _hwce_v4.cpuCtrlSlave_regAccessResync(self, reg, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.cpuCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_cpuCtrlSlave
    __del__ = lambda self: None
cpuCtrlSlave_swigregister = _hwce_v4.cpuCtrlSlave_swigregister
cpuCtrlSlave_swigregister(cpuCtrlSlave)

class cacheCtrlSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, cacheCtrlSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, cacheCtrlSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_cacheCtrlSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["enable"] = _hwce_v4.cacheCtrlSlave_enable_set
    __swig_getmethods__["enable"] = _hwce_v4.cacheCtrlSlave_enable_get
    if _newclass:
        enable = _swig_property(_hwce_v4.cacheCtrlSlave_enable_get, _hwce_v4.cacheCtrlSlave_enable_set)
    __swig_setmethods__["flushAll"] = _hwce_v4.cacheCtrlSlave_flushAll_set
    __swig_getmethods__["flushAll"] = _hwce_v4.cacheCtrlSlave_flushAll_get
    if _newclass:
        flushAll = _swig_property(_hwce_v4.cacheCtrlSlave_flushAll_get, _hwce_v4.cacheCtrlSlave_flushAll_set)
    __swig_setmethods__["flushLine"] = _hwce_v4.cacheCtrlSlave_flushLine_set
    __swig_getmethods__["flushLine"] = _hwce_v4.cacheCtrlSlave_flushLine_get
    if _newclass:
        flushLine = _swig_property(_hwce_v4.cacheCtrlSlave_flushLine_get, _hwce_v4.cacheCtrlSlave_flushLine_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.cacheCtrlSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.cacheCtrlSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.cacheCtrlSlave_resyncTarget_get, _hwce_v4.cacheCtrlSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.cacheCtrlSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.cacheCtrlSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.cacheCtrlSlave_initiatorEngine_get, _hwce_v4.cacheCtrlSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.cacheCtrlSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.cacheCtrlSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.cacheCtrlSlave_targetEngine_get, _hwce_v4.cacheCtrlSlave_targetEngine_set)

    def enableResync(self, enable: 'bool') -> "void":
        return _hwce_v4.cacheCtrlSlave_enableResync(self, enable)

    def flushAllResync(self) -> "void":
        return _hwce_v4.cacheCtrlSlave_flushAllResync(self)

    def flushLineResync(self, addr: 'unsigned int') -> "void":
        return _hwce_v4.cacheCtrlSlave_flushLineResync(self, addr)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.cacheCtrlSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_cacheCtrlSlave
    __del__ = lambda self: None
cacheCtrlSlave_swigregister = _hwce_v4.cacheCtrlSlave_swigregister
cacheCtrlSlave_swigregister(cacheCtrlSlave)

class regSlave(slavePort):
    __swig_setmethods__ = {}
    for _s in [slavePort]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, regSlave, name, value)
    __swig_getmethods__ = {}
    for _s in [slavePort]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, regSlave, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _hwce_v4.new_regSlave(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["regAccessMeth"] = _hwce_v4.regSlave_regAccessMeth_set
    __swig_getmethods__["regAccessMeth"] = _hwce_v4.regSlave_regAccessMeth_get
    if _newclass:
        regAccessMeth = _swig_property(_hwce_v4.regSlave_regAccessMeth_get, _hwce_v4.regSlave_regAccessMeth_set)
    __swig_setmethods__["resyncTarget"] = _hwce_v4.regSlave_resyncTarget_set
    __swig_getmethods__["resyncTarget"] = _hwce_v4.regSlave_resyncTarget_get
    if _newclass:
        resyncTarget = _swig_property(_hwce_v4.regSlave_resyncTarget_get, _hwce_v4.regSlave_resyncTarget_set)
    __swig_setmethods__["initiatorEngine"] = _hwce_v4.regSlave_initiatorEngine_set
    __swig_getmethods__["initiatorEngine"] = _hwce_v4.regSlave_initiatorEngine_get
    if _newclass:
        initiatorEngine = _swig_property(_hwce_v4.regSlave_initiatorEngine_get, _hwce_v4.regSlave_initiatorEngine_set)
    __swig_setmethods__["targetEngine"] = _hwce_v4.regSlave_targetEngine_set
    __swig_getmethods__["targetEngine"] = _hwce_v4.regSlave_targetEngine_get
    if _newclass:
        targetEngine = _swig_property(_hwce_v4.regSlave_targetEngine_get, _hwce_v4.regSlave_targetEngine_set)

    def regAccessResync(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _hwce_v4.regSlave_regAccessResync(self, slaveId, isRead, value)

    def regAccess(self, slaveId: 'int *', isRead: 'int', value: 'uint64_t *') -> "int":
        return _hwce_v4.regSlave_regAccess(self, slaveId, isRead, value)

    def getSlavePortResync(self, initiatorEngine: 'gv::clockEngine *', targetEngine: 'gv::clockEngine *') -> "gv::slavePort *":
        return _hwce_v4.regSlave_getSlavePortResync(self, initiatorEngine, targetEngine)
    __swig_destroy__ = _hwce_v4.delete_regSlave
    __del__ = lambda self: None
regSlave_swigregister = _hwce_v4.regSlave_swigregister
regSlave_swigregister(regSlave)


_hwce_v4.HWCE_STATE_IDLE_swigconstant(_hwce_v4)
HWCE_STATE_IDLE = _hwce_v4.HWCE_STATE_IDLE

_hwce_v4.HWCE_STATE_CONTEXT_COPY_swigconstant(_hwce_v4)
HWCE_STATE_CONTEXT_COPY = _hwce_v4.HWCE_STATE_CONTEXT_COPY

_hwce_v4.HWCE_STATE_LOCKED_swigconstant(_hwce_v4)
HWCE_STATE_LOCKED = _hwce_v4.HWCE_STATE_LOCKED

_hwce_v4.HWCE_JOBQUEUE_IDLE_swigconstant(_hwce_v4)
HWCE_JOBQUEUE_IDLE = _hwce_v4.HWCE_JOBQUEUE_IDLE

_hwce_v4.HWCE_JOBQUEUE_FETCH_WEIGHTS_swigconstant(_hwce_v4)
HWCE_JOBQUEUE_FETCH_WEIGHTS = _hwce_v4.HWCE_JOBQUEUE_FETCH_WEIGHTS

_hwce_v4.HWCE_JOBQUEUE_EXEC_CONV_swigconstant(_hwce_v4)
HWCE_JOBQUEUE_EXEC_CONV = _hwce_v4.HWCE_JOBQUEUE_EXEC_CONV
class Hwce_base(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Hwce_base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Hwce_base, name)
    __repr__ = _swig_repr

    def __init__(self, top: 'Hwce'):
        this = _hwce_v4.new_Hwce_base(top)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def init(self, base: 'uint32_t', lineLen: 'int', lineStride: 'int', featLen: 'int', featStride: 'int', nbFeatures: 'int', featLoop: 'int') -> "void":
        return _hwce_v4.Hwce_base_init(self, base, lineLen, lineStride, featLen, featStride, nbFeatures, featLoop)

    def get(self) -> "uint32_t":
        return _hwce_v4.Hwce_base_get(self)

    def update(self) -> "void":
        return _hwce_v4.Hwce_base_update(self)

    def reachedEof(self) -> "bool":
        return _hwce_v4.Hwce_base_reachedEof(self)

    def startFeature(self) -> "void":
        return _hwce_v4.Hwce_base_startFeature(self)
    __swig_destroy__ = _hwce_v4.delete_Hwce_base
    __del__ = lambda self: None
Hwce_base_swigregister = _hwce_v4.Hwce_base_swigregister
Hwce_base_swigregister(Hwce_base)

class hwce_job_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hwce_job_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hwce_job_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["next"] = _hwce_v4.hwce_job_t_next_set
    __swig_getmethods__["next"] = _hwce_v4.hwce_job_t_next_get
    if _newclass:
        next = _swig_property(_hwce_v4.hwce_job_t_next_get, _hwce_v4.hwce_job_t_next_set)
    __swig_setmethods__["id"] = _hwce_v4.hwce_job_t_id_set
    __swig_getmethods__["id"] = _hwce_v4.hwce_job_t_id_get
    if _newclass:
        id = _swig_property(_hwce_v4.hwce_job_t_id_get, _hwce_v4.hwce_job_t_id_set)
    __swig_setmethods__["runId"] = _hwce_v4.hwce_job_t_runId_set
    __swig_getmethods__["runId"] = _hwce_v4.hwce_job_t_runId_get
    if _newclass:
        runId = _swig_property(_hwce_v4.hwce_job_t_runId_get, _hwce_v4.hwce_job_t_runId_set)
    __swig_setmethods__["xoutSize"] = _hwce_v4.hwce_job_t_xoutSize_set
    __swig_getmethods__["xoutSize"] = _hwce_v4.hwce_job_t_xoutSize_get
    if _newclass:
        xoutSize = _swig_property(_hwce_v4.hwce_job_t_xoutSize_get, _hwce_v4.hwce_job_t_xoutSize_set)
    __swig_setmethods__["xinSize"] = _hwce_v4.hwce_job_t_xinSize_set
    __swig_getmethods__["xinSize"] = _hwce_v4.hwce_job_t_xinSize_get
    if _newclass:
        xinSize = _swig_property(_hwce_v4.hwce_job_t_xinSize_get, _hwce_v4.hwce_job_t_xinSize_set)
    __swig_setmethods__["xinLineStride"] = _hwce_v4.hwce_job_t_xinLineStride_set
    __swig_getmethods__["xinLineStride"] = _hwce_v4.hwce_job_t_xinLineStride_get
    if _newclass:
        xinLineStride = _swig_property(_hwce_v4.hwce_job_t_xinLineStride_get, _hwce_v4.hwce_job_t_xinLineStride_set)
    __swig_setmethods__["xinLineLength"] = _hwce_v4.hwce_job_t_xinLineLength_set
    __swig_getmethods__["xinLineLength"] = _hwce_v4.hwce_job_t_xinLineLength_get
    if _newclass:
        xinLineLength = _swig_property(_hwce_v4.hwce_job_t_xinLineLength_get, _hwce_v4.hwce_job_t_xinLineLength_set)
    __swig_setmethods__["xinFeatStride"] = _hwce_v4.hwce_job_t_xinFeatStride_set
    __swig_getmethods__["xinFeatStride"] = _hwce_v4.hwce_job_t_xinFeatStride_get
    if _newclass:
        xinFeatStride = _swig_property(_hwce_v4.hwce_job_t_xinFeatStride_get, _hwce_v4.hwce_job_t_xinFeatStride_set)
    __swig_setmethods__["xinFeatLength"] = _hwce_v4.hwce_job_t_xinFeatLength_set
    __swig_getmethods__["xinFeatLength"] = _hwce_v4.hwce_job_t_xinFeatLength_get
    if _newclass:
        xinFeatLength = _swig_property(_hwce_v4.hwce_job_t_xinFeatLength_get, _hwce_v4.hwce_job_t_xinFeatLength_set)
    __swig_setmethods__["xinBase"] = _hwce_v4.hwce_job_t_xinBase_set
    __swig_getmethods__["xinBase"] = _hwce_v4.hwce_job_t_xinBase_get
    if _newclass:
        xinBase = _swig_property(_hwce_v4.hwce_job_t_xinBase_get, _hwce_v4.hwce_job_t_xinBase_set)
    __swig_setmethods__["weightsBase"] = _hwce_v4.hwce_job_t_weightsBase_set
    __swig_getmethods__["weightsBase"] = _hwce_v4.hwce_job_t_weightsBase_get
    if _newclass:
        weightsBase = _swig_property(_hwce_v4.hwce_job_t_weightsBase_get, _hwce_v4.hwce_job_t_weightsBase_set)
    __swig_setmethods__["yinBase"] = _hwce_v4.hwce_job_t_yinBase_set
    __swig_getmethods__["yinBase"] = _hwce_v4.hwce_job_t_yinBase_get
    if _newclass:
        yinBase = _swig_property(_hwce_v4.hwce_job_t_yinBase_get, _hwce_v4.hwce_job_t_yinBase_set)
    __swig_setmethods__["youtBase"] = _hwce_v4.hwce_job_t_youtBase_set
    __swig_getmethods__["youtBase"] = _hwce_v4.hwce_job_t_youtBase_get
    if _newclass:
        youtBase = _swig_property(_hwce_v4.hwce_job_t_youtBase_get, _hwce_v4.hwce_job_t_youtBase_set)
    __swig_setmethods__["yLineStride"] = _hwce_v4.hwce_job_t_yLineStride_set
    __swig_getmethods__["yLineStride"] = _hwce_v4.hwce_job_t_yLineStride_get
    if _newclass:
        yLineStride = _swig_property(_hwce_v4.hwce_job_t_yLineStride_get, _hwce_v4.hwce_job_t_yLineStride_set)
    __swig_setmethods__["yLineLength"] = _hwce_v4.hwce_job_t_yLineLength_set
    __swig_getmethods__["yLineLength"] = _hwce_v4.hwce_job_t_yLineLength_get
    if _newclass:
        yLineLength = _swig_property(_hwce_v4.hwce_job_t_yLineLength_get, _hwce_v4.hwce_job_t_yLineLength_set)
    __swig_setmethods__["yFeatStride"] = _hwce_v4.hwce_job_t_yFeatStride_set
    __swig_getmethods__["yFeatStride"] = _hwce_v4.hwce_job_t_yFeatStride_get
    if _newclass:
        yFeatStride = _swig_property(_hwce_v4.hwce_job_t_yFeatStride_get, _hwce_v4.hwce_job_t_yFeatStride_set)
    __swig_setmethods__["yFeatLength"] = _hwce_v4.hwce_job_t_yFeatLength_set
    __swig_getmethods__["yFeatLength"] = _hwce_v4.hwce_job_t_yFeatLength_get
    if _newclass:
        yFeatLength = _swig_property(_hwce_v4.hwce_job_t_yFeatLength_get, _hwce_v4.hwce_job_t_yFeatLength_set)
    __swig_setmethods__["wof"] = _hwce_v4.hwce_job_t_wof_set
    __swig_getmethods__["wof"] = _hwce_v4.hwce_job_t_wof_get
    if _newclass:
        wof = _swig_property(_hwce_v4.hwce_job_t_wof_get, _hwce_v4.hwce_job_t_wof_set)
    __swig_setmethods__["nif"] = _hwce_v4.hwce_job_t_nif_set
    __swig_getmethods__["nif"] = _hwce_v4.hwce_job_t_nif_get
    if _newclass:
        nif = _swig_property(_hwce_v4.hwce_job_t_nif_get, _hwce_v4.hwce_job_t_nif_set)
    __swig_setmethods__["wstride"] = _hwce_v4.hwce_job_t_wstride_set
    __swig_getmethods__["wstride"] = _hwce_v4.hwce_job_t_wstride_get
    if _newclass:
        wstride = _swig_property(_hwce_v4.hwce_job_t_wstride_get, _hwce_v4.hwce_job_t_wstride_set)
    __swig_setmethods__["noyConst"] = _hwce_v4.hwce_job_t_noyConst_set
    __swig_getmethods__["noyConst"] = _hwce_v4.hwce_job_t_noyConst_get
    if _newclass:
        noyConst = _swig_property(_hwce_v4.hwce_job_t_noyConst_get, _hwce_v4.hwce_job_t_noyConst_set)
    __swig_setmethods__["lbufLen"] = _hwce_v4.hwce_job_t_lbufLen_set
    __swig_getmethods__["lbufLen"] = _hwce_v4.hwce_job_t_lbufLen_get
    if _newclass:
        lbufLen = _swig_property(_hwce_v4.hwce_job_t_lbufLen_get, _hwce_v4.hwce_job_t_lbufLen_set)
    __swig_setmethods__["regs"] = _hwce_v4.hwce_job_t_regs_set
    __swig_getmethods__["regs"] = _hwce_v4.hwce_job_t_regs_get
    if _newclass:
        regs = _swig_property(_hwce_v4.hwce_job_t_regs_get, _hwce_v4.hwce_job_t_regs_set)

    def __init__(self):
        this = _hwce_v4.new_hwce_job_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_hwce_job_t
    __del__ = lambda self: None
hwce_job_t_swigregister = _hwce_v4.hwce_job_t_swigregister
hwce_job_t_swigregister(hwce_job_t)

class Hwce(component):
    __swig_setmethods__ = {}
    for _s in [component]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Hwce, name, value)
    __swig_getmethods__ = {}
    for _s in [component]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Hwce, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nbMasterPorts"] = _hwce_v4.Hwce_nbMasterPorts_set
    __swig_getmethods__["nbMasterPorts"] = _hwce_v4.Hwce_nbMasterPorts_get
    if _newclass:
        nbMasterPorts = _swig_property(_hwce_v4.Hwce_nbMasterPorts_get, _hwce_v4.Hwce_nbMasterPorts_set)
    __swig_setmethods__["nbJobs"] = _hwce_v4.Hwce_nbJobs_set
    __swig_getmethods__["nbJobs"] = _hwce_v4.Hwce_nbJobs_get
    if _newclass:
        nbJobs = _swig_property(_hwce_v4.Hwce_nbJobs_get, _hwce_v4.Hwce_nbJobs_set)
    __swig_setmethods__["lineBufferWidth"] = _hwce_v4.Hwce_lineBufferWidth_set
    __swig_getmethods__["lineBufferWidth"] = _hwce_v4.Hwce_lineBufferWidth_get
    if _newclass:
        lineBufferWidth = _swig_property(_hwce_v4.Hwce_lineBufferWidth_get, _hwce_v4.Hwce_lineBufferWidth_set)
    __swig_setmethods__["lineBufferHeight"] = _hwce_v4.Hwce_lineBufferHeight_set
    __swig_getmethods__["lineBufferHeight"] = _hwce_v4.Hwce_lineBufferHeight_get
    if _newclass:
        lineBufferHeight = _swig_property(_hwce_v4.Hwce_lineBufferHeight_get, _hwce_v4.Hwce_lineBufferHeight_set)

    def build(self) -> "int":
        return _hwce_v4.Hwce_build(self)

    def __init__(self):
        this = _hwce_v4.new_Hwce()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _hwce_v4.delete_Hwce
    __del__ = lambda self: None
Hwce_swigregister = _hwce_v4.Hwce_swigregister
Hwce_swigregister(Hwce)

# This file is compatible with both classic and new-style classes.


